import React from "react"
import figma from "@figma/code-connect"
import RdsPopularPage from "./rds-popular-page"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPopularPage,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=110-39152",
  {
    props: {},
    example: (props) => <RdsPopularPage {...props} itemList={undefined} />,
  },
)
