import React from "react"
import RdsCompStackedChart from "./rds-comp-chart-stacked"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompStackedChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10033-13993",
  {
    props: {
      showFourthDataset: figma.boolean("Show Fourth Dataset"),
      showSecondDataset: figma.boolean("Show Second Dataset"),
      showLegend: figma.boolean("Show Legend"),
      showGrid: figma.boolean("Show Grid"),
      showThirdDataset: figma.boolean("Show Third Dataset"),
    },
    example: (props) => <RdsCompStackedChart
  dataSets={[
    {
      backgroundColor: '#62D5D9',
      borderColor: 'white',
      data: [
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142
      ],
      fill: true,
      label: 'My Second dataset'
    },
    {
      backgroundColor: '#928AE0',
      borderColor: 'white',
      data: [
        151,
        152,
        159,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162
      ],
      fill: true,
      label: 'My Third dataset'
    },
    {
      backgroundColor: '#EDB371',
      borderColor: 'white',
      data: [
        150,
        201,
        160,
        203,
        151,
        205,
        206,
        207,
        208,
        209,
        210,
        211
      ],
      fill: true,
      label: 'My Fourth dataset'
    }
  ]}
  id="Stacked_Chart"
  labels={[
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ]}
  options={{
    interaction: {
      axis: 'x',
      intersect: false,
      mode: 'nearest'
    },
    plugins: {
      legend: {
        labels: {
          usePointStyle: true
        },
        pointStyle: 'circle',
        tooltip: {
          usePointStyle: true
        }
      },
      title: {
        display: true,
        text: 'Chart.js Line Chart - stacked'
      },
      tooltip: {
        mode: 'index'
      }
    },
    pointStyle: 'triangle',
    radius: 3,
    scales: {
      x: {
        axis: 'x',
        beginAtZero: false,
        bounds: 'ticks',
        display: true,
        grace: 0,
        grid: {
          borderColor: 'rgba(0,0,0,0.1)',
          borderDash: [],
          borderDashOffset: 0,
          borderWidth: 1,
          color: 'rgba(0,0,0,0.1)',
          display: true,
          drawBorder: true,
          drawOnChartArea: true,
          drawTicks: true,
          lineWidth: 1,
          offset: false,
          tickLength: 8
        },
        id: 'x',
        offset: false,
        position: 'bottom',
        reverse: false,
        ticks: {
          align: 'center',
          autoSkip: true,
          autoSkipPadding: 3,
          backdropColor: 'rgba(255, 255, 255, 0.75)',
          backdropPadding: 2,
          color: '#666',
          crossAlign: 'near',
          display: true,
          labelOffset: 0,
          major: {},
          maxRotation: 50,
          minRotation: 0,
          minor: {},
          mirror: false,
          padding: 3,
          showLabelBackdrop: false,
          textStrokeColor: '',
          textStrokeWidth: 0
        },
        title: {
          color: '#666',
          display: true,
          padding: {
            bottom: 4,
            top: 4
          },
          text: 'Month'
        },
        type: 'category'
      },
      y: {
        axis: 'y',
        beginAtZero: false,
        bounds: 'ticks',
        display: true,
        grace: 0,
        grid: {
          borderColor: 'rgba(0,0,0,0.1)',
          borderDash: [],
          borderDashOffset: 0,
          borderWidth: 1,
          color: 'rgba(0,0,0,0.1)',
          display: true,
          drawBorder: true,
          drawOnChartArea: true,
          drawTicks: true,
          lineWidth: 1,
          offset: false,
          tickLength: 8
        },
        id: 'y',
        offset: false,
        position: 'left',
        reverse: false,
        stacked: true,
        ticks: {
          align: 'center',
          autoSkip: true,
          autoSkipPadding: 3,
          backdropColor: 'rgba(255, 255, 255, 0.75)',
          backdropPadding: 2,
          color: '#666',
          crossAlign: 'near',
          display: true,
          labelOffset: 0,
          major: {},
          maxRotation: 50,
          minRotation: 0,
          minor: {},
          mirror: false,
          padding: 3,
          showLabelBackdrop: false,
          textStrokeColor: '',
          textStrokeWidth: 0
        },
        title: {
          color: '#666',
          display: true,
          padding: {
            bottom: 4,
            top: 4
          },
          text: 'Value'
        },
        type: 'linear'
      }
    }
  }}
/>,
  },
)
