import React from "react"
import figma from "@figma/code-connect"
import RdsCounter from "./rds-counter"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCounter,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=702-19519",
  {
    props: {
      isMandatory: figma.boolean("❗ - Is Mandatory"),
      showTitle: figma.boolean("🆕 - Show Title"),
      changeTitle: figma.string("✏️ Change Title"),
      placeholderText: figma.string("✏️ Placeholder Text"),
      layout: figma.enum("📱 Layout", {
        "Right Side": "right-side",
        "Side to Side": "side-to-side",
        Bottom: "bottom",
      }),
      state: figma.enum("💡 State", {
        Default: "default",
        Selected: "selected",
        Disabled: "disabled",
      }),
    },
    example: (props) => <RdsCounter counterValue={0} min={0} max={0} width={0} {...props} />,
  },
)
