import React from "react"
import figma from "@figma/code-connect"
import RdsCounter, { LayoutOptions, CounterState } from "./rds-counter"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCounter,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=702-19519",
  {
    props: {
      isMandatory: figma.boolean("❗ - Is Mandatory"),
      showTitle: figma.boolean("🆕 - Show Title"),
     // changeTitle: figma.string("✏️ Change Title"),
     // placeholderText: figma.string("✏️ Placeholder Text"),
      layout: figma.enum("📱 Layout", {
        "Right Side": LayoutOptions.RightSide,
        "Side to Side": LayoutOptions.SideToSide,
        Bottom: LayoutOptions.Bottom,
      }),
      state: figma.enum("💡 State", {
        Default: CounterState.Default,
        Selected: CounterState.Selected,
        Disabled: CounterState.Disabled,
      }),
    },
    example: (props) => <RdsCounter  counterValue={0} min={0} max={50} width={280} 
    titleText="Label"
    placeholder="00"
    colorVariant="primary"
    {...props}/>,
  },
)
