import React from "react"
import figma from "@figma/code-connect"
import RdsToast, { ToastLayout, ToastLeadingIcon, ToastPosition, ToastState } from "./rds-toast"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsToast,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=925-3543",
  {
    props: {
      chatTime: figma.string("⏳ Timestamp"),
      showLeading: figma.boolean("👀 - Show Leading Icon"),
      //showTimestamp: figma.boolean("⏱️ - Show Timestamp"),
      //subtext: figma.string("✍ Subtext"),
      //headerText: figma.string("✏️ Header Text "),
      showSubText: figma.boolean("🔤 - Show Subtext"),
      //helpText: figma.string("✍ Help Text"),
      leadingIcon: figma.enum("❤️ Leading Icon", {
        Circle: ToastLeadingIcon.Circle,
        Plus: ToastLeadingIcon.Plus,
      }),
      showHeader: figma.boolean("📝 - Show Header"),
      showDismiss: figma.boolean("⛔️ - Show Dismiss"),
      //showSecondary: figma.boolean("🔶 - Show Secondary"),
      //showPrimary: figma.boolean("🔷 - Show Primary"),
      //showHelpText: figma.boolean("🔤 - Show Help Text"),
      layout: figma.enum("📱 Layout", {
        text: ToastLayout.Text,
        download: ToastLayout.Download,
        chat: ToastLayout.Chat,
        request: ToastLayout.Request,
        padded : ToastLayout.Padded,
      }),
      state: figma.enum("💡 State", {
        Basic: ToastState.Basic,
        Info: ToastState.Info,
        Success: ToastState.Success,
        Error: ToastState.Error,
      }),
    },
    example: (props) => <RdsToast   {...props}
    borderColor="primary"
    colorVariant="light"
    filename="Filename.txt"
    headerText="Toast Headline"
    placeholder="Placeholder Text"
    subText="This is a big sample placeholder text."
    position={ToastPosition.TopLeft}
    progressWidth={40}
    layout={ToastLayout.Text}
    leadingIcon={ToastLeadingIcon.Circle}    />,
  },
)
