import React from "react";
import figma from "@figma/code-connect";
import RdsColorPicker, { ColorMode, ColorPickerType, PickerType } from "./rds-color-picker";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsColorPicker,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=4080-409",
  {
    props: {
      type: figma.enum("⚠️ Type", {
        Default: ColorPickerType.Default,
        Button: ColorPickerType.Button,
        "Button - Expanded": ColorPickerType.ButtonExpanded,
      }),
    },
    example: (props) => (
      <RdsColorPicker
      label="Color-Picker"
      value="#e1e1e1"
      colorMode={ColorMode.HEX}
      pickerType={PickerType.Grid}
      showSwatches
      showTabs
      {...props} 
      />
    ),
  }
);
