import React from "react";
import figma from "@figma/code-connect";
import RdsColorPicker from "./rds-color-picker";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsColorPicker,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=4080-409",
  {
    props: {
      showSwatchList: figma.boolean("🎨 - Show Swatch List"),
      type: figma.enum("⚠️ Type", {
        Default: "default",
        Button: "button",
        "Button - Expanded": "button---expanded",
      }),
    },
    example: (props) => (
      <RdsColorPicker
        label="Default Label"
        value="Default Value"
        {...props} 
      />
    ),
  }
);
