import React from "react";
import RdsCompBillingAddress from "../../rds-comp-billing-address/rds-comp-billing-address";

export const code_actual = () => {
    return (
        <RdsCompBillingAddress countryList = {[
            { option: "Afghanistan" },
            { option: "Albania" },
            { option: "Belgium" },
            { option: "Belize" },
            { option: "Benin" },
            { option: "Bermuda" },
            { option: "Bhutan" },
            { option: "Cambodia" },
            { option: "Cameroon" },
            { option: "Canada" },
            { option: "Cayman Islands (the)" },
            { option: "Central African Republic (the)" },
            { option: "Chad" },
            { option: "Chile" },
            { option: "Falkland Islands (the) [Malvinas]" },
            { option: "Faroe Islands (the)" },
            { option: "Fiji" },
            { option: "Gibraltar" },
            { option: "Greece" },
            { option: "Hong Kong" },
            { option: "Hungary" },
            { option: "Iceland" },
            { option: "India" },
            { option: "Indonesia" },
            { option: "Iran (Islamic Republic of)" },
            { option: "Iraq" },
            { option: "Ireland" },
            { option: "Isle of Man" },
            { option: "Israel" },
            { option: "Italy" },
            { option: "Jamaica" },
            { option: "Japan" },
            { option: "Jersey" },
            { option: "Jordan" },
            { option: "Kazakhstan" },
            { option: "Kenya" },
            { option: "Kyrgyzstan" },
            { option: "Lao People's Democratic Republic (the)" },
            { option: "Latvia" },
            { option: "Lebanon" },
            { option: "Lesotho" },
            { option: "Marshall Islands (the)" },
            { option: "Martinique" },
            { option: "Namibia" },
            { option: "Nauru" },
            { option: "Nepal" },
            { option: "Netherlands (the)" },
            { option: "New Caledonia" },
            { option: "New Zealand" },
            { option: "Nicaragua" },
            { option: "Niger (the)" },
            { option: "Nigeria" },
            { option: "Niue" },
            { option: "Norfolk Island" },
            { option: "Northern Mariana Islands (the)" },
            { option: "Norway" },
            { option: "Oman" },
            { option: "Singapore" },
            { option: "Sint Maarten (Dutch part)" },
            { option: "Slovakia" },
            { option: "Slovenia" },
            { option: "Solomon Islands" },
            { option: "Somalia" },
            { option: "South Africa" },
            { option: "South Georgia and the South Sandwich Islands" },
            { option: "South Sudan" },
            { option: "Spain" },
            { option: "Sri Lanka" },
            { option: "Zimbabwe" },
            { option: "Åland Islands" }
        ]}

        IndianStateList = {[
            { option: "Andhra Pradesh" },
            { option: "Arunachal Pradesh" },
            { option: "Assam" },
            { option: "Bihar" },
            { option: "Chhattisgarh" },
            { option: "Goa" },
            { option: "Gujarat" },
            { option: "Haryana" },
            { option: "Himachal Pradesh" },
            { option: "Jammu and Kashmir" },
            { option: "Jharkhand" },
            { option: "Karnataka" },
            { option: "Kerala" },
            { option: "Madhya Pradesh" },
            { option: "Maharashtra" },
            { option: "Manipur" },
            { option: "Meghalaya" },
            { option: "Mizoram" },
            { option: "Nagaland" },
            { option: "Odisha" },
            { option: "Punjab" },
            { option: "Rajasthan" },
            { option: "Sikkim" },
            { option: "Tamil Nadu" },
            { option: "Telangana" },
            { option: "Tripura" },
            { option: "Uttarakhand" },
            { option: "Uttar Pradesh" },
            { option: "West Bengal" },
            { option: "Andaman and Nicobar Islands" },
            { option: "Chandigarh" },
            { option: "Dadra and Nagar Haveli" },
            { option: "Daman and Diu" },
            { option: "Delhi" },
            { option: "Lakshadweep" },
            { option: "Puducherry" }
        ]}
        BillingAddressDetails={()=>{}}
        />
    );
};

export default code_actual;