import React from "react"
import figma from "@figma/code-connect"
import RdsTreeStructure, { IconType, NodeState, TreeLevel } from "./rds-tree-structure"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTreeStructure,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1891-3859",
  {
    props: {
      level: figma.enum("📊 Level", {
        "Level 1": TreeLevel.Level1,
        "Level 2": TreeLevel.Level2,
        "Level 3": TreeLevel.Level3,
        "Level 4": TreeLevel.Level4,
      }),
    },
    example: (props) => <RdsTreeStructure {...props} 
    Language="CSS"
    showActions
    showCheckbox
    showChewron
    showFile
    showFolder
    state={NodeState.Default}
    text="Name"
    treeData={[
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    icon: 'file',
                    id: 4,
                    name: 'Name'
                  }
                ],
                icon: 'file',
                id: 3,
                name: 'Name'
              }
            ],
            icon: 'folder',
            id: 2,
            name: 'Name'
          }
        ],
        icon: 'folder',
        id: 1,
        name: 'Name'
      },
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    icon: 'file',
                    id: 8,
                    name: 'Name'
                  }
                ],
                icon: 'file',
                id: 7,
                name: 'Name'
              }
            ],
            icon: 'folder',
            id: 6,
            name: 'Name'
          }
        ],
        icon: 'folder',
        id: 5,
        name: 'Name'
      },
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    icon: 'file',
                    id: 12,
                    name: 'Name'
                  }
                ],
                icon: 'file',
                id: 11,
                name: 'Name'
              }
            ],
            icon: 'folder',
            id: 10,
            name: 'Name'
          }
        ],
        icon: 'folder',
        id: 9,
        name: 'Name'
      },
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    icon: 'file',
                    id: 16,
                    name: 'Name'
                  }
                ],
                icon: 'file',
                id: 15,
                name: 'Name'
              }
            ],
            icon: 'folder',
            id: 14,
            name: 'Name'
          }
        ],
        icon: 'folder',
        id: 13,
        name: 'Name'
      }
    ]}
    type={IconType.Folder}
    />,
  },
);
