import React from "react"
import figma from "@figma/code-connect"
import RdsTreeStructure from "./rds-tree-structure"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTreeStructure,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1891-3859",
  {
    props: {
      level: figma.enum("📊 Level", {
        "Level 1": "level1", 
        "Level 2": "level2",
        "Level 3": "level3",
        "Level 4": "level4",
      }),
    },
    example: (props) => <RdsTreeStructure {...props} />,
  },
);
