import React from "react"
import figma from "@figma/code-connect"
import RdsTreeStructure, { TreeLevel } from "./rds-tree-structure"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTreeStructure,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1891-3859",
  {
    props: {
      level: figma.enum("📊 Level", {
        "Level 1": TreeLevel.Level1,
        "Level 2": TreeLevel.Level2,
        "Level 3": TreeLevel.Level3,
        "Level 4": TreeLevel.Level4,
      }),
    },
    example: (props) => <RdsTreeStructure {...props} />,
  },
);
