import React from "react";
import figma from "@figma/code-connect";
import RdsDatepicker from "./rds-datepicker";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDatepicker,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=443-15972",
  {
    props: {
      isMandatory: figma.boolean("❗ - Is Mandatory"),
      showTitle: figma.boolean("🆕 - Show Title"),
      placeholderText: figma.string("✏️ Placeholder Text"),
      titleText: figma.string("✏️ Title Text"),
      changeIcon: figma.instance("🔃 Change Icon"),
      state: figma.enum("💡 State", {
        Default: "default",
        Expanded: "expanded",
        Selected: "selected",
      }),
      type: figma.enum("⚠️ Type", {
        Default: "default",
        Advanced: "advanced", // ✅ Updated value
        WithTime: "withTime", // ✅ Updated value
      }),
    },
    example: (props) => <RdsDatepicker isDropdownOpen={false} {...props} />,
  }
);
