import React from "react"
import figma from "@figma/code-connect"
import RdsTabGroup, { TabLayout } from "./rds-tab-group"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTabGroup,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=652-1488",
  {
    props: {
      level: figma.enum("📊 Level", {
        "Level 1": 1,
        "Level 2": 2,
        "Level 3": 3,
        "Level 4": 4,
        "Level 5": 5,
        "Level 6": 6,
        "Level 7": 7,
      }),
      layout: figma.enum("📱 Layout", {
        Horizontal: TabLayout.Horizontal,
        Vertical: TabLayout.Vertical,
      }),
      style: figma.enum("✨ Style", {
        "Bottom Select": "bottom-select",
        "Top Select": "top-select",
        "Bottom Select Alt": "bottom-select-alt",
        "Top Select Alt": "top-select-alt",
        "Background Filled": "background-filled",
        "Pill": "pill",
        "Select Tabs": "select-tabs",
        "Vertical - Alt Right Line": "vertical---alt-right-line",
        "Vertical - Alt Left Line": "vertical---alt-left-line",
        "Vertical - Left Line": "vertical---left-line",
        "Vertical - Right Line": "vertical---right-line",
        "Vertical - Left Filled": "vertical---left-filled",
        "Vertical - Pointer": "vertical---pointer",
        "Vertical - Flap": "vertical---flap",
      }),
    },
    example: (props) => <RdsTabGroup  {...props} />,
  },
)
