import React from "react"
import RdsCompESignature from "./rds-comp-e-signature"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompESignature,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=20743-4032",
  {
    props: {
      colourSwatch: figma.boolean("🎨 Colour Swatch"),
      mode: figma.enum("🌙 Mode", {
        "Draw": "draw",
        "Upload": "upload",
        "Choose":"choose"
      }),
      type: figma.enum("⚠️ Type", {
        "FullName": "fullname",
        "Initials": "initials"
      })
    },
    example: (props) => <RdsCompESignature {...props}
    disabled={false} 
    />,
  },
)
