import { defineConfig } from 'vitest/config';
import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';
import { playwright } from '@vitest/browser-playwright';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [
    react(),
    storybookTest({
      storybookScript: 'npm run storybook -- --ci',
      storybookUrl: 'http://localhost:6006',
    }),
  ],
  optimizeDeps: {
    // Pre-scan ALL story files so Vite bundles their deps before the first test
    // run, preventing mid-test page reloads that kill the vitest browser runner.
    entries: [
      './raaghu-elements/**/*.stories.tsx',
      './raaghu-components/**/*.stories.tsx',
      './raaghu-layouts/**/*.stories.tsx',
      './vitest.setup.ts',
    ],
    include: [
      '@testing-library/jest-dom/matchers',
      'react',
      'react-dom',
      'storybook/test',
      'storybook/preview-api',
      // MUI material subpath imports discovered mid-test
      '@mui/material/FormControl',
      '@mui/material/Select',
      '@mui/material/MenuItem',
      '@mui/material/IconButton',
      '@mui/material/ImageList',
      '@mui/material/ImageListItem',
      '@mui/material/Menu',
      '@mui/material/ListItemText',
      '@mui/material/SvgIcon',
      '@mui/material/Grid',
      // MUI lab
      '@mui/lab',
      '@mui/lab/Timeline',
      // MUI icons discovered mid-test
      '@mui/icons-material/Remove',
      '@mui/icons-material/KeyboardArrowDown',
      '@mui/icons-material/SwapVert',
      '@mui/icons-material/Star',
      '@mui/icons-material/NotificationImportant',
      '@mui/icons-material/ChevronRight',
      '@mui/icons-material/Check',
      '@mui/icons-material/AutoAwesomeOutlined',
      '@mui/icons-material/AutoAwesome',
      '@mui/icons-material/Attachment',
      '@mui/icons-material/PersonOutline',
      '@mui/icons-material/GroupOutlined',
      '@mui/icons-material/List',
      '@mui/icons-material/Refresh',
      '@mui/icons-material/FileUpload',
      '@mui/icons-material/Delete',
      '@mui/icons-material/Download',
      '@mui/icons-material/Forward10Outlined',
      '@mui/icons-material/RestoreOutlined',
      '@mui/icons-material/IosShare',
      '@mui/icons-material/PendingOutlined',
      '@mui/icons-material/CircleOutlined',
      '@mui/icons-material/SettingsSuggestSharp',
      '@mui/icons-material/VolumeUp',
      '@mui/icons-material/RemoveOutlined',
      '@mui/icons-material/AddOutlined',
      '@mui/icons-material/Search',
      '@mui/icons-material/EmojiEmotions',
      '@mui/icons-material/Pets',
      '@mui/icons-material/Restaurant',
      '@mui/icons-material/Flight',
      '@mui/icons-material/SportsFootball',
      '@mui/icons-material/Lightbulb',
      '@mui/icons-material/Favorite',
      '@mui/icons-material/Flag',
      '@mui/icons-material/OpenInFullOutlined',
      '@mui/icons-material/CodeOff',
      '@mui/icons-material/ColorizeOutlined',
      '@mui/icons-material/CalendarMonth',
      '@mui/icons-material/Computer',
      '@mui/icons-material/Cloud',
      '@mui/icons-material/InsertDriveFile',
      '@mui/icons-material/Send',
      '@mui/icons-material/MoreHoriz',
      '@mui/icons-material/ArrowUpward',
      '@mui/icons-material/ArrowDownward',
      '@mui/icons-material/InsertEmoticon',
      '@mui/icons-material/AttachmentOutlined',
      '@mui/icons-material/AlternateEmail',
      '@mui/icons-material/MailOutline',
      '@mui/icons-material/AccountCircle',
      '@mui/icons-material/Gif',
      '@mui/icons-material/PushPinOutlined',
      '@mui/icons-material/Edit',
      '@mui/icons-material/ThumbUpAlt',
      '@mui/icons-material/ThumbDownAlt',
      // Chart libraries
      'chart.js',
      'chart.js/auto',
      // Other discovered deps
      'react-syntax-highlighter/dist/esm/default-highlight',
      'react-syntax-highlighter/dist/esm/styles/hljs',
      'dayjs',
      'dayjs/plugin/customParseFormat',
      'react-measure',
      'react-color',
      'react-datepicker',
      'lottie-react',
      '@dnd-kit/core',
      '@dnd-kit/sortable',
      '@dnd-kit/utilities',
      'react-svg-worldmap',
    ],
    // These CJS packages use runtime require() for missing/peer deps (immutable,
    // draft-js). Excluding them prevents Vite's pre-bundle phase from crashing
    // at test startup. They are loaded on-demand by the browser at story render.
    exclude: [
      'markdown-to-jsx',
      'immutable',
      'draft-js',
      'html-to-draftjs',
      'react-draft-wysiwyg',
    ],
  },
  test: {
    browser: {
      enabled: true,
      provider: playwright(),
      instances: [{ browser: 'chromium' }],
    },
    setupFiles: [
      './vitest.setup.ts',
    ],
    coverage: {
      provider: 'istanbul',
      reporter: ['text', 'lcov', 'html'],
      include: [
        'raaghu-elements/**/*.{ts,tsx}',
        'raaghu-components/**/*.{ts,tsx}',
        'raaghu-layouts/**/*.{ts,tsx}',
      ],
      exclude: [
        '**/*.stories.{ts,tsx}',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
        '**/node_modules/**',
        '**/index.ts',
      ],
      thresholds: {
        statements: 60,
        branches: 50,
        functions: 60,
        lines: 60,
      },
    },
  },
});
