import React from "react"
import figma from "@figma/code-connect"
import RdsAlert, { AlertType } from "./rds-alert"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */


figma.connect(
  RdsAlert,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=611-982",
  {
    props: {
      showIcon: figma.boolean("👀 - Show Icon"),
      showLink: figma.boolean("🔗 - Show Link"),
      showTitle: figma.boolean("🆕 Show Title"),
      //changeIcon: figma.instance("🔃 Change Icon"),
      title: figma.string("✏️ Title"),
      showDescription: figma.boolean("〰 - Show Description"),
      showSecondary: figma.boolean("🔶 - Show Secondary"),
      showPrimary: figma.boolean("🔷 - Show Primary"),
      showDismiss: figma.boolean("⛔️ - Show Dismiss"),
      showButtons: figma.boolean("🕹️ - Show Buttons"),
      description: figma.string("✍ Description Line 1"),

        // Use enum values directly for the type property
        type: figma.enum("⚠️ Type", {
          Info: AlertType.info,
          Success: AlertType.success,
          Warning: AlertType.warning,
          Error: AlertType.error,
        }),
      
      multiline: figma.boolean("☰ Multiline"),
      size: figma.enum("Size", {
        Large: "large",
        Small: "small",
        Medium: "medium",
      }),
    },
    example: (props) => <RdsAlert {...props} icon="information" iconHeight="20px" iconWidth="20px" />,
  },
)
