import React from "react"
import RdsCompTimePicker from "./rds-comp-time-picker"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompTimePicker,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=858-4103",
  {
    props: {
      style:figma.enum("✨ Style",{
        "Default": "default",
        "Compact": "compact",
      }),
      state:figma.enum("💡 State",{
        "Default": "default",
        "Expanded": "expanded",
        "Selected": "selected",
      }),
    },
    example: (props) => <RdsCompTimePicker {...props} colorVariant="primary" disabled={false} />,
  },
)
