import React from "react"
import figma from "@figma/code-connect"
import RdsMixedChart from "./rds-chart-mixed"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsMixedChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9994-1930",
  {
    props: {
      showLineDataset: figma.boolean("Show Line Dataset"),
      showLegend: figma.boolean("Show Legend"),
      showBarDataset: figma.boolean("Show Bar dataset"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <RdsMixedChart {...props} labels={[]} options={undefined} dataSets={[]} chartStyle={""} id={""} />,
  },
)
