import React from "react"
import  RdsAvatar  from "./rds-avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=530-4297",
  {
    props: {
      activityRing: figma.boolean("⭕ Activity ring"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      title: figma.string("✏️ Title"),
      subtext: figma.string("✏️ Subtext"),
      showDesignation: figma.boolean("🔤 Show Designation"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      changeIcon: figma.instance("🔃 Change Icon"),
      showNameDesignation: figma.boolean("🔤 Show Name & Designation"),
    },
    example: (props) => <RdsAvatar />,
  },
)
