import React from "react"
import  RdsAvatar  from "./rds-avatar"
import figma from "@figma/code-connect"
import { display } from "@mui/system"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Single Avatar - With Name
figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=530-4297",
  {
    variant: { "✨ Style": "With Name" },
    props: {
      activityRing: figma.boolean("⭕ Activity ring"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      title: figma.string("✏️ Title"),
      subText: figma.string("✏️ Subtext"),
      showDesignation: figma.boolean("🔤 Show Designation"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      size: figma.enum("📏 Size",  {
        "Small": "small",
        "Medium": "medium",
        "Large": "large"
      }),
    },
    example: (props) => (
      <RdsAvatar 
        {...props}
        displayStyle="with-name"
      />
    ),
  }
)

// Single Avatar - Name On Bottom
figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=530-4297",
  {
    variant: { "✨ Style": "Name On Bottom" },
    props: {
      activityRing: figma.boolean("⭕ Activity ring"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      title: figma.string("✏️ Title"),
      subText: figma.string("✏️ Subtext"),
      showDesignation: figma.boolean("🔤 Show Designation"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      size: figma.enum("📏 Size",  {
        "Small": "small",
        "Medium": "medium",
        "Large": "large"
      }),
    },
    example: (props) => (
      <RdsAvatar 
        {...props}
        displayStyle="name-bottom"
      />
    ),
  }
)

// Stacked Avatars - with avatars array
figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=530-4297",
  {
    variant: { "✨ Style": "Stacking" },
    props: {
      activityRing: figma.boolean("⭕ Activity ring"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      showDesignation: figma.boolean("🔤 Show Designation"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      size: figma.enum("📏 Size",  {
        "Small": "small",
        "Medium": "medium",
        "Large": "large"
      }),
    },
    example: (props) => (
      <RdsAvatar 
        {...props}
        displayStyle="stacking"
        avatars={[
          {
            size: 'medium',
            src: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
            subText: 'Designation',
            title: 'Jane Doe'
          },
          {
            size: 'medium',
            src: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
            subText: 'Designation',
            title: 'John Smith'
          },
          {
            size: 'medium',
            src: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
            subText: 'Designation',
            title: 'Ava Lee'
          },
          {
            size: 'medium',
            src: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
            subText: 'Designation',
            title: 'Mike Brown'
          }
        ]}
      />
    ),
  }
)