import React from "react"
import figma from "@figma/code-connect"
import RdsStat from "./rds-stat"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsStat,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=97-185",
  {
    props: {
      layout: figma.enum("Layout", {
        Basic: "basic",
        Advanced: "advanced",
      }),
      type: figma.enum("Type", {
        Secondary: "secondary",
        Primary: "primary",
        Error: "error",
        Warning: "warning",
        Success: "success",
      }),
    },
    example: (props) => <RdsStat {...props}  items={[]} />,
  },
)
