import React from "react"
import RdsCompSpinner, { SpinnerLayout, SpinnerSize } from "./rds-comp-spinner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompSpinner,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=841-5077",
  {
    props: {
      showLabel: figma.boolean("✏️ Show Label"),
      labelText: figma.string("📝 Label Text"),
      size: figma.enum("📏 Size", {
        "Small": SpinnerSize.Small,
        "Medium": SpinnerSize.Medium,
        "Large": SpinnerSize.Large,
        "Default": SpinnerSize.Default,
      }),
      layout: figma.enum("📱 Layout", {
        "Label on bottom": SpinnerLayout.LabelOnBottom,
        "Label + Spinner": SpinnerLayout.LabelAndSpinner,
        "Spinner + Label": SpinnerLayout.SpinnerAndLabel,
        "Label on top": SpinnerLayout.LabelOnTop,
      }),
    },
    example: (props) => <RdsCompSpinner 
    {...props} 
    width="50px"
    colorVariant="primary"
    height="50px"
    spinnerType="border"
    />,
  },
)
