import type { Meta, StoryObj } from '@storybook/react-vite';
import RdsRadio from './rds-radio';

const meta: Meta<typeof RdsRadio> = {
  title: 'Elements/Radio',
  component: RdsRadio,
  parameters: {
    layout: 'padded',
    // hide these autogenerated controls from the Controls panel
    controls: {
    exclude: ['radioProps', 'ref'],
    },
  },
  tags: ['autodocs'],
  argTypes: {
    options: {
      control: 'object',
      description: 'Array of radio options',
    },
    direction: {
      control: 'select',
      options: ['row', 'column'],
      description: 'Direction of radio group layout',
    },
    layout: {
      control: 'select',
      options: ['icon', 'icon with label', 'icon with bottom label'],
      description: 'Layout configuration for radio buttons',
    },
    state: {
      control: 'select',
      options: ['default', 'hover', 'disabled'],
      description: 'State of the radio buttons',
    },
      value: {
        control: 'text',
        description: 'Selected value (leave empty for unchecked)',
        table: {
          defaultValue: { summary: 'undefined' },
        },
      },
  },
};

export default meta;
import React, { useState } from 'react';
type Story = StoryObj<typeof meta>;

const basicOptions = [
  { text: 'Option 1', value: 'option1' },
  { text: 'Option 2', value: 'option2' },
  { text: 'Option 3', value: 'option3' },
];

export const Default: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Choose an option',
    options: [{ text: 'Option 1', value: 'option1' }],
    value: undefined,
  },
};

export const Horizontal: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Horizontal Layout',
    options: basicOptions,
    direction: 'row',
    value: undefined,
  },
};

export const WithDisabledOptions: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Some Disabled Options',
    options: [
      { text: 'Available Option', value: 'option1' },
      { text: 'Disabled Option', value: 'option2', disabled: true },
      { text: 'Another Available', value: 'option3' },
      { text: 'Also Disabled', value: 'option4', disabled: true },
    ],
    value: undefined,
  },
};

export const WithSelectedValue: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Pre-selected Option',
    options:  [{ text: 'Option 1', value: 'option1' }],
    value: undefined,
  },
};

export const WithoutLabel: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    options: basicOptions,
    value: undefined,
  },
};

