import type { Meta, StoryObj } from '@storybook/react-vite';
import RdsRadio from './rds-radio';

const meta: Meta<typeof RdsRadio> = {
  title: 'Elements/Radio',
  component: RdsRadio,
  parameters: {
    layout: 'padded',
    // hide these autogenerated controls from the Controls panel
    controls: {
    exclude: ['radioProps', 'ref'],
    },
  },
  tags: ['autodocs'],
  argTypes: {
    options: {
      control: 'object',
      description: 'Array of radio options',
    },
    direction: {
      control: 'select',
      options: ['row', 'column'],
      description: 'Direction of radio group layout',
    },
    layout: {
      control: 'select',
      options: ['icon', 'icon with label', 'icon with bottom label'],
      description: 'Layout configuration for radio buttons',
    },
    state: {
      control: 'select',
      options: ['default', 'hover', 'disabled'],
      description: 'State of the radio buttons',
    },
      value: {
        control: 'text',
        description: 'Selected value (leave empty for unchecked)',
        table: {
          defaultValue: { summary: 'undefined' },
        },
      },
      selected: {
        control: 'boolean',
        description: 'Force selection (true selects first option, false clears). When undefined component behaves normally.',
        table: { defaultValue: { summary: 'undefined' } }
      },
  },
};

export default meta;
import React, { useState } from 'react';
type Story = StoryObj<typeof meta>;

const basicOptions = [
  { text: 'Option 1', value: 'option1' },
  { text: 'Option 2', value: 'option2' },
  { text: 'Option 3', value: 'option3' },
];

// Helper pattern: when args.selected is defined we force selection/clearing; otherwise allow interactive local state.
function computeForcedValue(args: any) {
  if (typeof args.selected === 'undefined') return undefined; // signal no forcing
  if (args.selected === true) {
    const first = (args.options || []).find((o: any) => !o.disabled);
    return first ? first.value : undefined;
  }
  return undefined; // selected === false -> clear
}

export const Default: Story = {
  render: (args) => {
    const [internal, setInternal] = useState<string | undefined>(args.value ?? undefined);
    const forced = computeForcedValue(args);
    const valueToUse = forced !== undefined || args.selected === false ? forced : internal;
    return (
      <RdsRadio
        {...args}
        value={valueToUse}
        onChange={(_e, val) => {
          if (typeof args.selected === 'undefined') setInternal(val);
        }}
      />
    );
  },
  args: {
    label: 'Choose an option',
    options: [{ text: 'Option 1', value: 'option1' }],
    value: undefined,
    selected: true,
  },
};
Default.parameters = { controls: { include: ['label','options','value','selected', 'direction','layout','state'] } };


export const Horizontal: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Horizontal Layout',
    options: basicOptions,
    direction: 'row',
    value: undefined,
  },
};
Horizontal.parameters = { controls: { include: ['label','options','value', 'direction','layout','state'] } };

export const WithDisabledOptions: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Some Disabled Options',
    options: [
      { text: 'Available Option', value: 'option1' },
      { text: 'Disabled Option', value: 'option2', disabled: true },
      { text: 'Another Available', value: 'option3' },
      { text: 'Also Disabled', value: 'option4', disabled: true },
    ],
    value: undefined,
  },
};
WithDisabledOptions.parameters = { controls: { include: ['label','options','value', 'direction','layout','state'] } };


export const WithSelectedValue: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    label: 'Pre-selected Option',
    options:  [{ text: 'Option 1', value: 'option1' }],
    value: undefined,
  },
};
WithSelectedValue.parameters = { controls: { include: ['label','options','value', 'direction','layout','state'] } };


export const WithoutLabel: Story = {
  render: (args) => {
    const [selected, setSelected] = useState(args.value ?? undefined);
    return (
      <RdsRadio
        {...args}
        value={selected}
        onChange={(_event, value) => setSelected(value)}
      />
    );
  },
  args: {
    options: basicOptions,
    value: undefined,
  },
};
WithoutLabel.parameters = { controls: { include: ['label','options','value', 'direction','layout','state'] } };

