import React from "react"
import  RdsRadio  from "./rds-radio"
import figma from "@figma/code-connect"
import { Dir } from "fs"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsRadio,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=346-3467",
  {
    props: {
      //label: figma.string("✏️Text"),
      layout: figma.enum("📱 Layout", {
        "Icon": "icon",
        "Icon with Label": "icon with label",
        "Icon with bottom Label": "icon with bottom label"
      }),
      state: figma.enum("💡 State", {
        "Default": "default",
        "Hover": "hover",
        "Disabled": "disabled"
      }),
      // selected: figma.enum("⚠️ Selected", {
      //   "On": "true",
      //   "Off": "false"
      // })
      // direction: figma.enum("Direction", {
      //   "Row": "row",
      //   "Column": "column"
      // }),
    },
    example: (props) => <RdsRadio
      options={[
        {
          text: 'Option 1',
          value: 'option1'
        }
      ]}
      {...props} />,
  },
)
