import React from "react"
import figma from "@figma/code-connect"
import { RdsTruncateText } from ".."
import { TruncateTextState } from "./rds-truncate-text";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTruncateText,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=998-59",
  {
    props: {
      text: figma.string("Text"),
      state: figma.enum("💡 State", {
        Default: TruncateTextState.Default,
        Hover: TruncateTextState.Hover,
      }),
    },
    example: (props) => (
      <RdsTruncateText {...props} maxLength={100} />
    ),
  }
);
