import React from "react"
import figma from "@figma/code-connect"
import RdsTextEditor from "./rds-text-editor"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTextEditor,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=385-697",
  {
    props: {
      isMandatory: figma.boolean("❗ Is Mandatory"),
      label: figma.string("📝Label"),
      showTitle: figma.boolean("✏️Show Title"),
      state: figma.enum("💡 State", {
        Default: "default",
        Active: "active",
        Selected: "selected",
        Disabled: "disabled",
        Error: "error",
      }),
    },
    example: (props) => <RdsTextEditor {...props} />,
  },
)
