import React from "react"
import  RdsBadge  from "./rds-badge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBadge,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=386-3365",
  {
    props: {
      //changeIcon: "🔃", // Use a string or the correct type expected by RdsBadgeProps
      size:figma.enum("📏 Size", { "Small": "small", "Medium": "medium", "Large": "large" }),
      shape:figma.enum("⚠️ Shape", { "Rectangle": "rectangle","Pill":"pill" }),
      layout:figma.enum("📱 Layout", { 
        "Text Only": "text", 
        "Icon Only": "icon",
        "Left Icon+Text": "icon-text", 
        "Right Icon+Text": "text-icon" }),
     // selectType: figma.enum("🔽 Select Type", { "Primary": "primary", "Outlined": "outlined", "Transparent": "transparent" }),
      state:figma.enum("💡 State", {
          Default: "default",
          Disabled: "disabled",
        }),
      colorVariant: figma.enum("⚠️ Type", {
        "Primary": "primary",
        "Secondary": "secondary",
        "Tertiary": "tertiary",
        "Danger": "danger",
        "Warning": "warning",
        "Light": "light",
        "Success": "success",
      }),
      styleType: figma.enum("✨ Style", {
        "Primary": "primary",
        "Outline": "outline",
        "Transparent": "transparent",
      }),
    },
      example: (props) => <RdsBadge badgeContent="Badge" {...props} />,
  },
)
