import React from "react"
import figma from "@figma/code-connect"
import RdsDropdown, { DisplayType, Layout, Shape, State, TooltipPlacement } from "./rds-dropdown"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDropdown,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=484-11217",
  {
    props: {
      state: figma.enum("💡 State", {
        Default: State.Default,
        Hover: State.Hover,
        Selected: State.Selected,
      }),
    },
    example: (props) => <RdsDropdown 
      colorVariant="primary"
      listItems={[
        {
          id: '1',
          label: 'Option 1',
          path: ''
        },
        {
          id: '2',
          label: 'Option 2',
          path: ''
        },
        {
          id: '3',
          label: 'Option 3',
          path: ''
        }
      ]}
      id="1"
      iconStroke
      profileImage="https://www.svgrepo.com/show/497407/profile-circle.svg"
      selectIcon="circle"
      showChevron
      tooltip
      tooltipTitle="This is tooltip"
      displayType={DisplayType.Dropdown}
      layout={Layout.IconText}
      shape={Shape.Rectangle}
      size="medium"
      states={State.Default}
      tooltipPlacement={TooltipPlacement.Right}
      darkDropdown={false} 
      label="Click Here" 
      {...props}    
      />,
  },
)
