import React from "react"
import figma from "@figma/code-connect"
import RdsButtonGroup from "./rds-button-group"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsButtonGroup,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=29-1049",
  {
    props: {
      layout: figma.enum("📱 Layout", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
    },
    example: (props) => <RdsButtonGroup {...props} vertical={false} isOutline={false} size={""} role={"checkbox"} buttonGroupItems={[]} />,
  },
)
