import React from "react";
import figma from "@figma/code-connect";
import RdsCompAlertPopup from "./rds-comp-alert-popup";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompAlertPopup,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1982-23802",
  {
    props: {
      //showIcon: figma.boolean("Show Icon"),
     // showDescription: figma.boolean("Show Description"),
    },
    example: (props) => (
      <>
        <RdsCompAlertPopup
          alertConfirmation="Are you sure to Delete?"
          alertID="alert_popup"
          cancelBtnLabel="Cancel"
          colorVariant="danger"
          deleteBtnLabel="Delete"
          iconUrl="delete"
          messageAlert="This record will be deleted permanently."
          type="default"
          {...props}
        />
        
        <button
          className="btn btn-primary"
          data-bs-target="#alert_popup"
          data-bs-toggle="modal"
          type="button"
        >
          ALERT POPUP
        </button>
      </>
    ),
  }
);
