import React from "react"
import  RdsCompVideoPlayer  from "./rds-comp-video-player"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompVideoPlayer,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=709-2556",
  {
    props: {
      type: figma.enum("⚠️ Type", {
        Default: "Default",
        Youtube: "YouTube",
        Vimeo: "Vimeo",
      }),
    },
    example: (props) => <RdsCompVideoPlayer {...props} width="480px" height="240px" autoplay={false} muted={false} videoLink="" />,
  },
)
