import React from "react"
import figma from "@figma/code-connect"
import RdsAccordion from "./rds-accordion"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAccordion,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=513-2027",
  {
    props: {
      title: figma.string("✏️ Title"),
      changeLeftIcon: figma.instance("🔃 Change Left Icon"),
      showLeftIcon: figma.boolean("⬅️ Show Left Icon"),
      size: figma.enum("📏 Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      layout: figma.enum("📱 Layout", {
        Default: "default",
        Expanded: "expanded",
      }),
      state: figma.enum("💡 State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
      }),
      style: figma.enum("✨ Style", {
        Border: "border",
        "No Border": "no-border",
        "Base Line": "base-line",
      }),
    },
    example: (props) => (
      <RdsAccordion items={[]} {...props}/>
    ),
  },
)

