import React from "react"
import figma from "@figma/code-connect"
import RdsAccordion, { AccordionBorder, AccordionLayout, AccordionSize, AccordionState } from "./rds-accordion"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAccordion,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=513-2027",
  {
    props: {
      size: figma.enum("📏 Size", {
        Small: AccordionSize.small,
        Medium: AccordionSize.medium,
        Large: AccordionSize.large,
      }),
      layout: figma.enum("📱 Layout", {
        Default: AccordionLayout.default,
        Expanded: AccordionLayout.expanded,
      }),
      state: figma.enum("💡 State", {
        Default: AccordionState.default,
        Hover: AccordionState.hover,
        Selected: AccordionState.selected,
      }),
      style: figma.enum("✨ Style", {
        Border: AccordionBorder.border,
        "No Border": AccordionBorder.borderhide,
        "Base Line": AccordionBorder.bottomline,
      }),
    },
    example: (props) => (
      <RdsAccordion
        {...props}
        items={[
          {
            accordionContent: <div className="border p-4"><p>Replace with your content component</p></div>,
            id: '1',
            title: 'Accordion Title 1'
          },

        ]}
      />
    ),
  },
)
