import React from "react"
import figma from "@figma/code-connect"
import RdsChat, { Comment } from "./rds-chat"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsChat,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=692-20694",
  {
    props: {
  
    },
    example: (props) => (
      <RdsChat 
        {...props} 
        OtherUserCommentTextColor="#202020"
        currentUserCommentBgColor="#7825E9"
        currentUserCommentTextColor="#FEF7FF"
        isChatScreenEnabled = {true}
        handleAddComment={() => {}}
        otherUserCommentBgColor="#D6D6D6"
        userData={[
          {
            activeDotButton: true,
            colorVariant: 'primary',
            comments: [
              {
                comment: 'Hi, How are you?',
                firstName: 'Alice',
                lastName: 'Smith'
              },
              {
                comment: 'This is sample message.',
                firstName: 'Alice',
                lastName: 'Smith'
              }
            ],
            firstName: 'Wai',
            lastName: 'Technologies',
            messageStatus: 'sent',
            profilePic: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU',
            size: 'medium',
            status: 'Typing....',
            time: '13.00'
          },
          {
            activeDotButton: false,
            colorVariant: 'primary',
            comments: [],
            firstName: 'Nikhil',
            lastName: 'Kasar',
            messageStatus: '',
            profilePic: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0m5Cy4lXCbuyG54L0vuo3i5-ALavHe9KmhWA_wDM&s',
            size: 'medium',
            status: 'Developer',
            time: '13.00'
          },
          {
            activeDotButton: false,
            colorVariant: 'primary',
            comments: [],
            firstName: 'Supriya',
            lastName: 'Tambe',
            messageStatus: '',
            profilePic: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0m5Cy4lXCbuyG54L0vuo3i5-ALavHe9KmhWA_wDM&s',
            size: 'medium',
            status: 'Company Owner',
            time: '13.00'
          }
        ]}
      />
    ),
  },
);