import React from "react"
import figma from "@figma/code-connect"
import RdsChat, { Comment } from "./rds-chat"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsChat,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=692-20694",
  {
    props: {
      message: figma.enum("🗨️ Message", {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
      }),
    },
    example: (props) => (
      <RdsChat 
        {...props} 
        isChatScreenEnabled={false} 
        userData={[]} 
        handleAddComment={() => {}}
      />
    ),
  },
);