import React from "react";
import { ComponentStory, ComponentMeta } from "@storybook/react";
import RdsCompBillingAddress from "./rds-comp-billing-address";

export default {
    title: "Components/Billing Address",
    component: RdsCompBillingAddress,
} as ComponentMeta<typeof RdsCompBillingAddress>;

const Template: ComponentStory<typeof RdsCompBillingAddress> = (args) => (
    <RdsCompBillingAddress {...args} />
);

export const BillingAddress = Template.bind({});
BillingAddress.args = {
    countryList: [
        { option: "Afghanistan" },
        { option: "Albania" },
        { option: "Algeria" },
        { option: "American Samoa" },
        { option: "Andorra" },
        { option: "Angola" },
        { option: "Anguilla" },
        { option: "Antarctica" },
        { option: "Antigua and Barbuda" },
        { option: "Argentina" },
        { option: "Armenia" },
        { option: "Aruba" },
        { option: "Australia" },
        { option: "Austria" },
        { option: "Azerbaijan" },
        { option: "Bahamas (the)" },
        { option: "Bahrain" },
        { option: "Bangladesh" },
        { option: "Barbados" },
        { option: "Belarus" },
        { option: "Belgium" },
        { option: "Belize" },
        { option: "Benin" },
        { option: "Bermuda" },
        { option: "Bhutan" },
        { option: "Bolivia (Plurinational State of)" },
        { option: "Bonaire}, S{option:int Eustatius and Saba" },
        { option: "Bosnia and Herzegovina" },
        { option: "Botswana" },
        { option: "Bouvet Island" },
        { option: "Brazil" },
        { option: "British Indian Ocean Territory (the)" },
        { option: "Brunei Darussalam" },
        { option: "Bulgaria" },
        { option: "Burkina Faso" },
        { option: "Burundi" },
        { option: "Cabo Verde" },
        { option: "Cambodia" },
        { option: "Cameroon" },
        { option: "Canada" },
        { option: "Cayman Islands (the)" },
        { option: "Central African Republic (the)" },
        { option: "Chad" },
        { option: "Chile" },
        { option: "China" },
        { option: "Christmas Island" },
        { option: "Cocos (Keeling) Islands (the)" },
        { option: "Colombia" },
        { option: "Comoros (the)" },
        { option: "Congo (the Democratic Republic of the)" },
        { option: "Congo (the)" },
        { option: "Cook Islands (the)" },
        { option: "Costa Rica" },
        { option: "Croatia" },
        { option: "Cuba" },
        { option: "Curaçao" },
        { option: "Cyprus" },
        { option: "Czechia" },
        { option: "Côte d'Ivoire" },
        { option: "Denmark" },
        { option: "Djibouti" },
        { option: "Dominica" },
        { option: "Dominican Republic (the)" },
        { option: "Ecuador" },
        { option: "Egypt" },
        { option: "El Salvador" },
        { option: "Equatorial Guinea" },
        { option: "Eritrea" },
        { option: "Estonia" },
        { option: "Eswatini" },
        { option: "Ethiopia" },
        { option: "Falkland Islands (the) [Malvinas]" },
        { option: "Faroe Islands (the)" },
        { option: "Fiji" },
        { option: "Finland" },
        { option: "France" },
        { option: "French Guiana" },
        { option: "French Polynesia" },
        { option: "French Southern Territories (the)" },
        { option: "Gabon" },
        { option: "Gambia (the)" },
        { option: "Georgia" },
        { option: "Germany" },
        { option: "Ghana" },
        { option: "Gibraltar" },
        { option: "Greece" },
        { option: "Greenland" },
        { option: "Grenada" },
        { option: "Guadeloupe" },
        { option: "Guam" },
        { option: "Guatemala" },
        { option: "Guernsey" },
        { option: "Guinea" },
        { option: "Guinea-Bissau" },
        { option: "Guyana" },
        { option: "Haiti" },
        { option: "Heard Island and McDonald Islands" },
        { option: "Holy See (the)" },
        { option: "Honduras" },
        { option: "Hong Kong" },
        { option: "Hungary" },
        { option: "Iceland" },
        { option: "India" },
        { option: "Indonesia" },
        { option: "Iran (Islamic Republic of)" },
        { option: "Iraq" },
        { option: "Ireland" },
        { option: "Isle of Man" },
        { option: "Israel" },
        { option: "Italy" },
        { option: "Jamaica" },
        { option: "Japan" },
        { option: "Jersey" },
        { option: "Jordan" },
        { option: "Kazakhstan" },
        { option: "Kenya" },
        { option: "Kiribati" },
        { option: "Korea (the Democratic People's Republic of)" },
        { option: "Korea (the Republic of)" },
        { option: "Kuwait" },
        { option: "Kyrgyzstan" },
        { option: "Lao People's Democratic Republic (the)" },
        { option: "Latvia" },
        { option: "Lebanon" },
        { option: "Lesotho" },
        { option: "Liberia" },
        { option: "Libya" },
        { option: "Liechtenstein" },
        { option: "Lithuania" },
        { option: "Luxembourg" },
        { option: "Macao" },
        { option: "Madagascar" },
        { option: "Malawi" },
        { option: "Malaysia" },
        { option: "Maldives" },
        { option: "Mali" },
        { option: "Malta" },
        { option: "Marshall Islands (the)" },
        { option: "Martinique" },
        { option: "Mauritania" },
        { option: "Mauritius" },
        { option: "Mayotte" },
        { option: "Mexico" },
        { option: "Micronesia (Federated States of)" },
        { option: "Moldova (the Republic of)" },
        { option: "Monaco" },
        { option: "Mongolia" },
        { option: "Montenegro" },
        { option: "Montserrat" },
        { option: "Morocco" },
        { option: "Mozambique" },
        { option: "Myanmar" },
        { option: "Namibia" },
        { option: "Nauru" },
        { option: "Nepal" },
        { option: "Netherlands (the)" },
        { option: "New Caledonia" },
        { option: "New Zealand" },
        { option: "Nicaragua" },
        { option: "Niger (the)" },
        { option: "Nigeria" },
        { option: "Niue" },
        { option: "Norfolk Island" },
        { option: "Northern Mariana Islands (the)" },
        { option: "Norway" },
        { option: "Oman" },
        { option: "Pakistan" },
        { option: "Palau" },
        { option: "Palestine}, S{option:tate of" },
        { option: "Panama" },
        { option: "Papua New Guinea" },
        { option: "Paraguay" },
        { option: "Peru" },
        { option: "Philippines (the)" },
        { option: "Pitcairn" },
        { option: "Poland" },
        { option: "Portugal" },
        { option: "Puerto Rico" },
        { option: "Qatar" },
        { option: "Republic of North Macedonia" },
        { option: "Romania" },
        { option: "Russian Federation (the)" },
        { option: "Rwanda" },
        { option: "Réunion" },
        { option: "Saint Barthélemy" },
        { option: "Saint Helena}, A{option:scension and Tristan da Cunha" },
        { option: "Saint Kitts and Nevis" },
        { option: "Saint Lucia" },
        { option: "Saint Martin (French part)" },
        { option: "Saint Pierre and Miquelon" },
        { option: "Saint Vincent and the Grenadines" },
        { option: "Samoa" },
        { option: "San Marino" },
        { option: "Sao Tome and Principe" },
        { option: "Saudi Arabia" },
        { option: "Senegal" },
        { option: "Serbia" },
        { option: "Seychelles" },
        { option: "Sierra Leone" },
        { option: "Singapore" },
        { option: "Sint Maarten (Dutch part)" },
        { option: "Slovakia" },
        { option: "Slovenia" },
        { option: "Solomon Islands" },
        { option: "Somalia" },
        { option: "South Africa" },
        { option: "South Georgia and the South Sandwich Islands" },
        { option: "South Sudan" },
        { option: "Spain" },
        { option: "Sri Lanka" },
        { option: "Sudan (the)" },
        { option: "Suriname" },
        { option: "Svalbard and Jan Mayen" },
        { option: "Sweden" },
        { option: "Switzerland" },
        { option: "Syrian Arab Republic" },
        { option: "Taiwan" },
        { option: "Tajikistan" },
        { option: "Tanzania}, U{option:nited Republic of" },
        { option: "Thailand" },
        { option: "Timor-Leste" },
        { option: "Togo" },
        { option: "Tokelau" },
        { option: "Tonga" },
        { option: "Trinidad and Tobago" },
        { option: "Tunisia" },
        { option: "Turkey" },
        { option: "Turkmenistan" },
        { option: "Turks and Caicos Islands (the)" },
        { option: "Tuvalu" },
        { option: "Uganda" },
        { option: "Ukraine" },
        { option: "United Arab Emirates (the)" },
        { option: "United Kingdom of Great Britain and Northern Ireland (the)" },
        { option: "United States Minor Outlying Islands (the)" },
        { option: "United States of America (the)" },
        { option: "Uruguay" },
        { option: "Uzbekistan" },
        { option: "Vanuatu" },
        { option: "Venezuela (Bolivarian Republic of)" },
        { option: "Viet Nam" },
        { option: "Virgin Islands (British)" },
        { option: "Virgin Islands (U.S.)" },
        { option: "Wallis and Futuna" },
        { option: "Western Sahara" },
        { option: "Yemen" },
        { option: "Zambia" },
        { option: "Zimbabwe" },
        { option: "Åland Islands" }
    ],

    IndianStateList: [
        { option: "Andhra Pradesh" },
        { option: "Arunachal Pradesh" },
        { option: "Assam" },
        { option: "Bihar" },
        { option: "Chhattisgarh" },
        { option: "Goa" },
        { option: "Gujarat" },
        { option: "Haryana" },
        { option: "Himachal Pradesh" },
        { option: "Jammu and Kashmir" },
        { option: "Jharkhand" },
        { option: "Karnataka" },
        { option: "Kerala" },
        { option: "Madhya Pradesh" },
        { option: "Maharashtra" },
        { option: "Manipur" },
        { option: "Meghalaya" },
        { option: "Mizoram" },
        { option: "Nagaland" },
        { option: "Odisha" },
        { option: "Punjab" },
        { option: "Rajasthan" },
        { option: "Sikkim" },
        { option: "Tamil Nadu" },
        { option: "Telangana" },
        { option: "Tripura" },
        { option: "Uttarakhand" },
        { option: "Uttar Pradesh" },
        { option: "West Bengal" },
        { option: "Andaman and Nicobar Islands" },
        { option: "Chandigarh" },
        { option: "Dadra and Nagar Haveli" },
        { option: "Daman and Diu" },
        { option: "Delhi" },
        { option: "Lakshadweep" },
        { option: "Puducherry" }
    ]
};

