import React from "react"
import figma from "@figma/code-connect"
import RdsFeatureList from "./rds-feature-list"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsFeatureList,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=146-16228",
  {
    props: {
      style: figma.enum("✨ Style", {
        "Single Column": "single-column",
        "Double Column": "double-column",
      }),
      type: figma.enum("⚠️ Type", {
        Default: "default",
        Primary: "primary",
        Secondary: "secondary",
        Success: "success",
        Warning: "warning",
        Error: "error",
      }),
    },
    example: (props) => <RdsFeatureList {...props} heading={"Feature"} itemList={[]} columns={0} />,
  },
)
