import React from "react"
import figma from "@figma/code-connect"
import RdsDialog from "./rds-dialog"
import { ColorVariant } from "../rds-rating/rds-rating"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDialog,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=533-7957",
  {
    props: {
      showTitle: figma.boolean("🆕 Show Title"),
      showSecondary: figma.boolean("🔶 Show Secondary"),
      title: figma.string("✏️ Title"),
      showPrimary: figma.boolean("🔷 Show Primary"),
      showDismiss: figma.boolean("⛔️ Show Dismiss"),
      size: figma.enum("📏 Size", {
        Large: "large",
        Small: "small",
      }),
      style: figma.enum("✨ Style", {
        Default: "default",
        Outlined: "outlined",
        Filled: "filled",
      }),
    },
    example: (props) => <RdsDialog 
    Size={props.size}
    Style={props.style}
    ShowDissmiss
    ShowPrimary
    ShowSecondary
    ShowTitle
    Title="Delete Account"
    ColorVariant={ColorVariant.Primary}
    Content="Deleting this data will remove your account and you will no longer login to the application! Are you sure you want to proceed?"
    Icon="users"
    ContentPosition="Bottom"/>,
  },
)
