import React from "react"
import figma from "@figma/code-connect"
import RdsPagination from "./rds-pagination"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPagination,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=702-6035",
  {
    props: {
      showManualInput: figma.boolean("✍ - Show Manual Input"),
      showLast: figma.boolean("➡️ - Show Last"),
      showFirst: figma.boolean("⬅️ - Show First"),
      legendTextTitle: figma.string("✏️ Legend Text / Title"),
      legendText: figma.boolean("📝 - Legend Text"),
      showDropdown: figma.boolean("🔽 - Show Dropdown"),
      style: figma.enum("✨ Style", {
        "Style 1": "style-1",
        "Style 2": "style-2",
        "Style 3": "style-3",
        "Style 4": "style-4",
        "Style 5": "style-5",
        "Style 6": "style-6",
        "Style 7": "style-7",
        "Style 8": "style-8",
        "Style 9": "style-9",
        "Style 10": "style-10",
        "Style 11": "style-11",
      }),
    },
    example: (props) => <RdsPagination totalRecords={0} {...props} />,
  },
)
