import React from "react"
import figma from "@figma/code-connect"
import RdsRating from "./rds-rating"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsRating,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=885-1971",
  {
    props: {
      type: figma.enum("⚠️ Type", {
        Star: "star",
        Slider: "slider",
      }),
      level: figma.enum("📊 Level", {
        Left: "left",
        Mid: "mid",
        Right: "right",
      }), 
      style: figma.enum("✨ Style", {
        Default: "default",
        Filled: "filled",
        Outline: "outline",
      }),
    },
    example: (props) => <RdsRating type={props.type} style={props.style} level={props.level} />,
  }
);

