import React from "react"
import figma from "@figma/code-connect"
import RdsRating, { ColorVariant, RatingLevel, RatingStyle, RatingType } from "./rds-rating"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsRating,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=885-1971",
  {
    props: {
      type: figma.enum("⚠️ Type", {
        Star: RatingType.Star,
        Slider: RatingType.Slider,
      }),
      rating: figma.enum("📊 Level", {
        "0": RatingLevel.Zero,
        "0.5": RatingLevel.ZeroPointFive,
        "1": RatingLevel.One,
        "1.5": RatingLevel.OnePointFive,
        "2": RatingLevel.Two,
        "2.5": RatingLevel.TwoPointFive,
        "3": RatingLevel.Three,
        "3.5": RatingLevel.ThreePointFive,
        "4": RatingLevel.Four,
        "4.5": RatingLevel.FourPointFive,
        "5": RatingLevel.Five,
        Left: RatingLevel.Left,
        Mid: RatingLevel.Mid,
        Right: RatingLevel.Right,
      }),
      style: figma.enum("✨ Style", {
        Default: RatingStyle.Default,
        Filled: RatingStyle.Filled,
        Outline: RatingStyle.Outline,
      }),

    },
    example: (props) => <RdsRating {...props} colorVariant={ColorVariant.Primary} />,
  },
)
