import React from "react"
import RdsCompFilterButton from "./rds-comp-filter-button"
import figma from "@figma/code-connect"
import { Circle } from "@mui/icons-material"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompFilterButton,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=19624-7036",
  {
    props: {},
    example: (props) => <RdsCompFilterButton
  filters={[
    {
      id: 'filter1',
      name: 'Filter Name',
      selectedValues: [],
      values: [
        'Option 1',
        'Option 2',
        'Option 3'
      ]
    },
    {
      id: 'filter2',
      name: 'Filter Name',
      selectedValues: [],
      values: [
        'Value A',
        'Value B',
        'Value C'
      ]
    },
    {
      id: 'filter3',
      name: 'Filter Name',
      selectedValues: [],
      values: [
        'Choice 1',
        'Choice 2',
        'Choice 3'
      ]
    }
  ]}
  leftIcon={<Circle sx={{fontSize: 16}} />}
  onApply={() => {}}
  onClear={() => {}}
  onFiltersChange={() => {}}
  rightIcon={<Circle sx={{fontSize: 16}} />}
  shape="rectangle"
  showLeftIcon
  showRightIcon
  text="Filter"
/>,
  },
)
