import React from "react"
import  RdsDivider  from "./rds-divider"
import figma from "@figma/code-connect"
import { text } from "stream/consumers"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDivider,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=817-19911",
  {
    props: {
      layout: figma.enum("📱 Layout", {
        "Horizontal": "horizontal",
        "Vertical": "vertical",
      }),
    },
    example: (props) => <RdsDivider
    textAlign="center"
    dividerMessage="Default Divider"
    iconShow
    {...props} />,
  },
)
