import React from "react"
import  RdsCounter  from "./rds-counter"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCounter  ,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=702-19519",
  {
    props: {
      showTitle: figma.boolean("🆕 - Show Title"),
      titleText: figma.string("✏️ Change Title"),
      isMandatory: figma.boolean("❗ - Is Mandatory"),
      disabled: figma.boolean("💡 State"),
    },
  example: (props) => <RdsCounter 
  min={0} 
  max={50} 
  {...props} 
  placeholder={0} 
  disabled={false}
  onChange={() => {}} />, 
  },
)
