import React from "react"
import figma from "@figma/code-connect"
import RdsFileUploader, { FileUploaderState, FileUploaderStyle } from "./rds-file-uploader"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsFileUploader,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=484-5419",
  {
    props: {
      attachmentStyle: figma.instance("🔗 Attachment Style"),
      hintText: figma.string("✏️ Hint"),
      isMandatory: figma.boolean("❗ Is Mandatory"),
      title: figma.string("✏️ Title"),
      showHint: figma.boolean("💬 Show Hint"),
      showTitle: figma.boolean("🆕 Show Title"),  
      state: figma.enum("💡 State", {
        Default: FileUploaderState.Default,
        Selected: FileUploaderState.Selected,
      }),
      style: figma.enum("✨ Style", {
        Basic: FileUploaderStyle.Basic,
        "Drop Area - Side Icon": FileUploaderStyle.DropAreaSideIcon,
        "Drop Area - Top Icon": FileUploaderStyle.DropAreaTopIcon,
        "Drop Area - With Upload Button": FileUploaderStyle.DropAreaWithUploadButton,
      }),
    },
    example: (props) => <RdsFileUploader  {...props}  extensions={""} label={"Title"}  multiple showThumbnail placeholderImage={""} />,
  },
)
