import React from "react"
import  RdsCompBooleanChart  from "./rds-comp-chart-boolean"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompBooleanChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9923-4213",
  {
    props: {
      iconSwap: figma.instance("Icon Swap"),
      showIcon: figma.boolean("Show Icon"),
    },
    example: (props) => <RdsCompBooleanChart
    {...props}
  centerIconName="users"
  dataSets={[
    {
      backgroundColor: [
        "var(--rds-semantic-success-main, #01AE9D)",
        "var(--rds-surface-subtle, #E1E1E1)"
      ],
      borderColor: [
        "var(--rds-neutral-0, #fff)"
      ],
      borderWidth: 1,
      cutout: '90%',
      data: [
        20,
        10
      ],
      fillRect: [
        200,
        100,
        40,
        10
      ],
      fillStyle: 'blue',
      label: 'Dataset 1',
      title: {
        dockInsidePlotArea: true,
        text: 'Doughnut Chart',
        verticalAlign: 'center'
      }
    }
  ]}
  id="BooleanId"
  labels={[
    'green',
    'grey'
  ]}
  options={{
    cutoutPercentage: 75,
    elements: {
      center: {
        text: '50%'
      }
    },
    legend: {
      display: false
    },
    maintainAspectRatio: false,
    plugins: {
      doughnutlabel: {
        labels: [
          {
            font: {
              size: 20,
              weight: 'bold'
            },
            text: '550'
          },
          {
            text: 'total'
          }
        ]
      },
      legend: {
        align: 'center',
        display: false,
        position: 'top'
      },
      series: {
        label: {
          display: false,
          position: 'inside',
          text: 'total'
        }
      }
    },
    responsive: true,
    scales: {}
  }}
/>,
  },
)
