import React from "react"
import figma from "@figma/code-connect"
import RdsCheckbox, { CheckboxState, CheckboxStatus, CheckboxStyle, LabelPosition } from "./rds-checkbox"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCheckbox,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=353-4642",
  {
    props: {
      showText: figma.boolean("✏️ Show Text"),
      labelText: figma.string("📝 - Label Text"),
      status: figma.enum("❄️ Status", {
        Checked: CheckboxStatus.Checked,
        Unchecked: CheckboxStatus.Unchecked,
        Indeterminate: CheckboxStatus.Indeterminate,
      }),
      style: figma.enum("✨ Style", {
        Square: CheckboxStyle.Square,
        Circular: CheckboxStyle.Circular,
      }),
      state: figma.enum("💡 State", {
        Default: CheckboxState.Default,
        Disabled : CheckboxState.Disabled,
        Hover: CheckboxState.Hover,
      }),
  },
    example: (props) => (
      <RdsCheckbox
        {...props}
        labelPosition={LabelPosition.Right}
      />
    ),
  }
);