import React from "react"
import figma from "@figma/code-connect"
import RdsCheckbox from "./rds-checkbox"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCheckbox,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=353-4642",
  {
    props: {
      showText: figma.boolean("✏️ Show Text"),
      labelText: figma.string("📝 - Label Text"),
      status: figma.enum("❄️ Status", {
        Checked: "checked",
        Unchecked: "unchecked",
        Indeterminate: "indeterminate",
      }),
      style: figma.enum("✨ Style", {
        Square: "square",
        Circular: "circular",
      }),
      state: figma.enum("💡 State", {
        Checkbox: "Checkbox",
        Indeterminate: "Indeterminate",
        Error: "ErrorCheckbox",
      }),
    },
    example: (props) => (
      <RdsCheckbox
        {...props}
        checked={props.status ? props.status === "checked" : false}
        label={props.labelText}
        state={props.state} 
      />
    ),
  }
);