import React from "react"
import  RdsCompToast, { ToastLayout, ToastLeadingIcon, ToastState }  from "./rds-comp-toast"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompToast,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=925-3543",
  {
    props: {
      chatTime: figma.string("⏳ Timestamp"),
      showHeader: figma.boolean("📝 - Show Header"),
      showDismiss: figma.boolean("⛔️ - Show Dismiss"),
      showSubText: figma.boolean("🔤 - Show Subtext"),
      layout: figma.enum("📱 Layout", {
        Text: ToastLayout.Text,
        Download: ToastLayout.Download,
        Chat: ToastLayout.Chat,
        Request: ToastLayout.Request,
      }),
      state: figma.enum("💡 State", {
        Basic: ToastState.Basic,
        Success: ToastState.Success,
        Error: ToastState.Error,
        Info: ToastState.Info,
      }),
      // leadingIcon: figma.enum("❤️ Leading Icon", {
      //   Circle: ToastLeadingIcon.Circle,
      //   Plus: ToastLeadingIcon.Plus
      // }),
    },
    example: (props) => <RdsCompToast 
    borderColor="primary"
    progressWidth={40}
    filename="Filename.txt"
    headerText="Toast Headline"
    placeholder="Placeholder Text"
    subText="This is a big sample placeholder text." 
    showLeading={true}
    leadingIcon={ToastLeadingIcon.Circle} 
    {...props} />,
  },
)
