import React from "react"
import RdsCompScrollBar, { ScrollBarType, ScrollPosition } from "./rds-comp-scrollbar"
import figma from "@figma/code-connect"
import { positions } from "@mui/system"
import { ArrowDropDown, ArrowDropUp } from "@mui/icons-material"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompScrollBar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=3410-47650",
  {
    props: {
      showButtons: figma.boolean("🕹️ - Show Buttons"),
      type: figma.enum("⚠️ Type", {
        "Mac": ScrollBarType.Mac,
        "Simple": ScrollBarType.Simple,
      }),
      position: figma.enum("📍 Position", {
        "Start": ScrollPosition.Start,
        "Middle": ScrollPosition.Middle,
        "End": ScrollPosition.End,
      }),
    },
    example: (props) => <RdsCompScrollBar 
    startIcon={<ArrowDropUp/>}
    endIcon={<ArrowDropDown/>}
    {...props} />,
  },
)
