import React from "react"
import figma from "@figma/code-connect"
import RdsBubbleChart from "./rds-chart-bubble"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBubbleChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9923-4721",
  {
    props: {
      showDataset2: figma.boolean("Show Dataset 2"),
      showLegend: figma.boolean("Show Legend"),
      showDataset1: figma.boolean("Show Dataset 1"),
      showGrid: figma.boolean("Show Grid"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <RdsBubbleChart {...props} id={""} labels={[]} options={undefined} dataSets={[]} />,
  },
)
