import React from "react"
import figma from "@figma/code-connect"
import RdsCarousel from "./rds-carousel"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCarousel,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1539-9671",
  {
    props: {
      style: figma.enum("✨ Style", {
        Default: "Default",
        "With Title": "with Title",
        "Full Width Image": "Full Width Image",
      }),
      state: figma.enum("💡 State", {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
      }),
    },
    example: (props) => <RdsCarousel Indicators={true}  type="Line"  controls={true}
    carouselItems={[
      {
        id: 1,
        imgUrl: 'https://cdn.londonandpartners.com/visit/london-organisations/tower-bridge/86830-640x360-tower-bridge-640.jpg',
        name: 'Sam Smith',
        subTitle: 'Nulla metus metus ullamcorper vel tincidunt set euismod nibh quisque volutpat condimentum.'
      },
      {
        id: 2,
        imgUrl: 'https://cdn.londonandpartners.com/-/media/images/london/visit/things-to-do/sightseeing/london-attractions/coca-cola-london-eye/the-london-eye-2-640x360.jpg?mw=640&hash=F7D574072DAD523443450DF57E3B91530064E4EE',
        name: 'king John',
        subTitle: 'this is the caption section were u can add the caption for the image'
      },
      {
        id: 3,
        imgUrl: 'https://cdn.londonandpartners.com/visit/london-organisations/tower-bridge/86830-640x360-tower-bridge-640.jpg',
        name: 'John Doe',
        subTitle: 'Nulla metus metus ullamcorper vel tincidunt set euismod nibh quisque volutpat condimentum.'
      },
      {
        id: 4,
        imgUrl: 'https://cdn.londonandpartners.com/-/media/images/london/visit/things-to-do/sightseeing/london-attractions/coca-cola-london-eye/the-london-eye-2-640x360.jpg?mw=640&hash=F7D574072DAD523443450DF57E3B91530064E4EE',
        name: 'User',
        subTitle: 'Nulla metus metus ullamcorper vel tincidunt set euismod nibh quisque volutpat condimentum.'
      }
    ]} />,
  },
)
