import React from "react";
import  RdsCompBubbleChart  from "./rds-comp-chart-bubble";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompBubbleChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9923-4721",
  {
    props: {
      showGrid: figma.boolean("Show Grid"),
      showDataset1: figma.boolean("Show Dataset 1"),
      showLegend: figma.boolean("Show Legend"),
      showDataset2: figma.boolean("Show Dataset 2"),
    },
    example: (props) => (
      <RdsCompBubbleChart
        {...props}
        dataSets={[
          {
            backgroundColor: ["rgba(255, 99, 132)"],
            borderColor: ["red"],
            data: [90, 97, 20, 30, 40, 50, 60, 70],
            label: "Dataset 1",
          },
          {
            backgroundColor: ["rgba(255, 206, 86)"],
            borderColor: ["orange"],
            data: [90, 80, 70, 60, 50, 40, 30, 90, 98],
            label: "Dataset 2",
          },
        ]}
        id="bubblecha"
        labels={[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]}
        options={{
          maintainAspectRatio: false,
          plugins: {
            legend: {
              labels: {
                usePointStyle: true,
              },
              pointStyle: "line",
              position: "top",
            },
            title: {
              display: true,
              text: "Bubble Chart",
            },
            tooltip: {
              usePointStyle: true,
            },
          },
          pointStyle: "triangle",
          radius: 10,
          responsive: true,
          scales: {
            x: {
              axis: "x",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: () => {},
                tickLength: 8,
                tickWidth: () => {},
              },
              id: "x",
              offset: false,
              position: "bottom",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                minor: {},
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "linear",
            },
            y: {
              axis: "y",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: () => {},
                tickLength: 8,
                tickWidth: () => {},
              },
              id: "y",
              offset: false,
              position: "left",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                minor: {},
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "linear",
            },
          },
        }}
      />
    ),
  }
);
