import React from "react"
import figma from "@figma/code-connect"
import RdsPopover, { PopoverState } from "./rds-popover"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPopover,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1509-4672",
  {
    props: {
      state: figma.enum("💡 State", {
        "No Arrow": PopoverState.NoArrow,
        "Top Left": PopoverState.TopLeft,
        "Top Centre": PopoverState.TopCentre,
        "Top Right": PopoverState.TopRight,
        "Bottom Left": PopoverState.BottomLeft,
        "Bottom Centre": PopoverState.BottomCentre,
        "Bottom Right": PopoverState.BottomRight,
        "Left Top": PopoverState.LeftTop,
        "Left Centre": PopoverState.LeftCentre,
        "Left Bottom": PopoverState.LeftBottom,
        "Right Bottom": PopoverState.RightBottom,
        "Right Centre": PopoverState.RightCentre,
        "Right Top": PopoverState.RightTop,
      }),
    },
    example: (props) => <RdsPopover  children={<p>Replace with your content component </p>} {...props} />,
  },
)
