import React from "react"
import figma from "@figma/code-connect"
import RdsPopover from "./rds-popover"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPopover,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1509-4672",
  {
    props: {
      state: figma.enum("💡 State", {
        "No Arrow": "no-arrow",
        "Top Left": "top-left",
        "Top Centre": "top-centre",
        "Top Right": "top-right",
        "Bottom Left": "bottom-left",
        "Bottom Centre": "bottom-centre",
        "Bottom Right": "bottom-right",
        "Left Top": "left-top",
        "Left Centre": "left-centre",
        "Left Bottom": "left-bottom",
        "Right Bottom": "right-bottom",
        "Right Centre": "right-centre",
        "Right Top": "right-top",
      }),
    },
    example: (props) => <RdsPopover children={""} popoverPosition={""} {...props} />,
  },
)
