import React from "react"
import figma from "@figma/code-connect"
import { RdsTooltip } from ".."

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTooltip,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=591-9150",
  {
    props: {
      label: figma.string("✏️ Label"),
      style: figma.enum("✨ Style", {
        "No Arrow": "no-arrow",
        "Middle Top Arrow": "middle-top-arrow",
        "Middle Bottom Arrow": "middle-bottom-arrow",
        "Left Arrow": "left-arrow",
        "Left Top Arrow": "left-top-arrow",
        "Left Bottom Arrow": "left-bottom-arrow",
        "Right Arrow": "right-arrow",
        "Right Top Arrow": "right-top-arrow",
        "Right Bottom Arrow": "right-bottom-arrow",
      }),
    },
    example: (props) => <RdsTooltip {...props} children={''} />,
  },
)
