import React from "react"
import  RdsTabs  from "./rds-tabs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTabs,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=380-3338",
  {
    props: {
      // showLeftIcon: figma.boolean("⬅️ - Show Left Icon"),
      // textTitle: figma.string("✏️ Text / Title"),
      // leftIcon: figma.instance("❤️ Left Icon"),
      // showRightIcon: figma.boolean("➡️ - Show Right Icon"),
      // rightIcon: figma.instance("❤️ Right Icon"),
      type:figma.enum("⚠️ Type", {
        Horizontal: "horizontal",
        Vertical: "vertical"
      }),
      layout: figma.enum("📱 Layout", {
        "Filled": "filled",
        "Flap": "flap",
        "Line - Bottom": "line-bottom",
        "Line - Bottom Solid": "line-bottom-solid",
        "Line - Left": "line-left",
        "Line - Left Solid": "line-left-solid",
        "Line - Right": "line-right",
        "Line - Right Solid": "line-right-solid",
        "Line - Top": "line-top",
        "Line - Top Solid": "line-top-solid",
        "Pill": "pill"
      }),
      state: figma.enum("💡 State", {
        "Default": "default",
        "Hover": "hover",
        "Selected": "selected",
        "Disabled": "disabled"
      }),
    },
    example: (props) => <RdsTabs 
    tabs={[
      {
        disabled: false,
        icon: undefined,
        id: 0,
        label: 'Overview'
      }
    ]} 
    activeTab={0}
    {...props} />,
  },
)
