import React from "react";
import RdsCompPieChart from "./rds-comp-chart-pie";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompPieChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10057-1579",
  {
    props: {},
    example: (props) => (
      <RdsCompPieChart
        dataSets={[
          {
            backgroundColor: [
              "#ff6384",
              "#ff9f40",
              "#ffcd56",
              "#4bc0c0",
              "#059bff",
            ],
            borderColor: ["#fff"],
            borderWidth: 1,
            data: [20, 10, 20, 40, 10],
            label: "Dataset1",
          },
        ]}
        id="chart pie"
        labels={["red", "Orange", "Yellow", "Green", "Blue"]}
        options={{
          animation: {
            animateRotate: false,
            animateScale: true,
          },
          circumference: 360,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              labels: {
                boxHeight: 10,
                boxWidth: 10,
                height: 5,
                padding: 30,
                pointStyleWidth: 13,
                usePointStyle: true,
              },
              pointStyle: "line",
              position: "top",
            },
            title: {
              display: true,
              text: "Pie Chart",
            },
          },
          responsive: true,
        }}
        radius={100}
      />
    ),
  }
);
