import React from "react"
import figma from "@figma/code-connect"
import RdsAddressDetail from "./rds-address-detail"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAddressDetail,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=19-18",
  {
    props: {
      showTitle: figma.boolean("Show Title"),
      showIcon: figma.boolean("Show Icon"),
      style: figma.enum("Style", {
        Default: "default",
        Outline: "outline",
      }),
      addressDetails: figma.enum("Address Details", {
        "Detail Address Line 1": "detail-address-line-1",
        "Detail Address Line 2": "detail-address-line-2",
        "Detail Address Line 3": "detail-address-line-3",
      }),
    },
    example: (props) => <RdsAddressDetail {...props} children={""}/>,
  },
)
