import React from "react"
import figma from "@figma/code-connect"
import RdsSideNav from "./rds-side-nav"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsSideNav,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=810-12671",
  {
    props: {
      platform: figma.instance("💻 Platform"),
      layout: figma.enum("📱 Layout", {
        Raaghu: "raaghu",
        Lists: "lists",
        Toolbar: "toolbar",
      }),
      type: figma.enum("⚠️ Type", {
        Collapsed: "collapsed",
        Expanded: "expanded",
        Fixed: "fixed",
      }),
    },
    example: (props) => <RdsSideNav {...props} sideNavItems={undefined} />,
  },
)
