import React from "react"
import figma from "@figma/code-connect"
import RdsSideNav, { NavLayout, NavType, Platform } from "./rds-side-nav"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsSideNav,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=810-12671",
  {
    props: {
      platform: figma.enum("💻 Platform", {
        Web: Platform.Web,
        Mobile: Platform.Mobile,
        SideNavigationABPList: Platform.SideNavigationABPList,
        SideNavigationANZList: Platform.SideNavigationANZList,
      }),
      layout: figma.enum("📱 Layout", {
        Raaghu: NavLayout.Raaghu,
        Lists: NavLayout.List,
        Toolbar: NavLayout.Toolbar,
      }),
      type: figma.enum("⚠️ Type", {
        Collapsed: NavType.Collapsed,
        Expanded: NavType.Expanded,
        Fixed: NavType.Fixed,
      }),
    },
    example: (props) => <RdsSideNav  {...props} platform={props.platform} sideNavItems={undefined} />,
  },
)
