import React from "react";
import RdsCompDoughnutChart from "./rds-comp-chart-doughnut";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompDoughnutChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9943-1272",
  {
    props: {
      subtext: figma.string("Subtext"),
      titleText: figma.string("Title Text"),
    },
    example: (props) => (
      <RdsCompDoughnutChart
        {...props}
        dataSets={[
          {
            backgroundColor: [
              "#ff6384",
              "#ff9f40",
              "#ffcd56",
              "#4bc0c0",
              "#0000FF",
            ],
            borderColor: ["#fff"],
            data: [20, 10, 20, 40, 10],
            label: "Dataset 1",
          },
        ]}
        id="myChart"
        labels={["Red", "Orange", "Yellow", "Green", "Blue"]}
        options={{
          maintainAspectRatio: false,
          options: {
            maintainAspectRatio: false,
            plugins: {
              legend: {
                position: "top",
              },
              subTitle: {
                fontColor: "#fff",
              },
              title: {
                display: true,
                text: "Chart.js Doughnut Chart",
              },
            },
            responsive: true,
          },
          plugins: {},
          scales: {},
          type: "doughnut",
        }}
        subTitleText="deioj"
        titleText="35 k"
      />
    ),
  }
);
