import React from "react"
import  RdsCompToolbar  from "./rds-comp-toolbar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompToolbar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=659-5688",
  {
    props: {
      layout:figma.enum("📱 Layout", {
        Primary: "primary",
        Secondary: "secondary",
      }),
      // state: figma.enum("💡 State", {
      //   Off: "off",
      //   On: "on",
      //   "Disabled On": "disabled-on",
      //   "Disabled Off": "disabled-off",
      // }),
      type:figma.enum("⚠️ Type", {
        'Inline Editor': 'inline-editor',
        'Full Featured': 'full-featured',
        'More Text': 'more-text',
        'More Paragraph': 'more-paragraph',
        'More Rich Content': 'more-rich-content',
        'Misc': 'misc',
      }),
    },
    example: (props) => <RdsCompToolbar {...props} />,
  },
)
