import React from "react"
import  RdsCompToolbar, { ToolbarLayout, ToolbarType }  from "./rds-comp-toolbar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompToolbar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=659-5688",
  {
    props: {
      layout:figma.enum("📱 Layout", {
        Primary: ToolbarLayout.Primary,
        Secondary: ToolbarLayout.Secondary,
      }),
      // state: figma.enum("💡 State", {
      //   Off: "off",
      //   On: "on",
      //   "Disabled On": "disabled-on",
      //   "Disabled Off": "disabled-off",
      // }),
      type:figma.enum("⚠️ Type", {
        'Inline Editor': ToolbarType.InlineEditor,
        'Full Featured': ToolbarType.FullFeatured,
        'More Text': ToolbarType.MoreText,
        'More Paragraph': ToolbarType.MoreParagraph,
        'More Rich Content': ToolbarType.MoreRichContent,
        'Misc': ToolbarType.Misc,
      }),
    },
    example: (props) => <RdsCompToolbar {...props} />,
  },
)
