import React from "react"
import RdsCompCodeSnippet from "./rds-comp-code-snippet"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompCodeSnippet,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=22743-11606",
  {
    props: {
      codeLines: figma.boolean("👨‍💻 Code Lines"),
      language: figma.boolean("✍ Language"),
      theme:figma.enum("🌙 Mode",{
        "Light": "light",
        "Dark": "dark"
      }),
      type: figma.enum("⚠️Type", {
        "Single Line": "singleLine",
        "Multi Line": "multiLine"
      })
    },
    example: (props) => <RdsCompCodeSnippet 
    {...props}
      code="<!DOCTYPE html>
              <html lang=&quot;en&quot;>
              <head>
                  <meta charset=&quot;UTF-8&quot;>
                  <meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;>
                  <title>Snippet Example</title>
              </head>
              <body>
                  <h1>Hello, World!</h1>
                  <p>This is a simple HTML snippet.</p>
              </body>
              </html>"
    />,
  },
)
