import React from "react"
import  RdsTooltip  from "./rds-tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTooltip,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=591-9150",
  {
    props: {
      title: figma.string("✏️ Label"),
      style: figma.enum("✨ Style", {
        "Middle Bottom Arrow":"top",
        "Middle Top Arrow":"bottom",
        "Right Arrow":"left",
        "Right Bottom Arrow":"top",
        "Right Top Arrow":"bottom",
        "Left Arrow":"right",
        "Left Bottom Arrow":"top",
        "Left Top Arrow":"bottom"
      }),
    },
    example: (props) =>   
     <RdsTooltip {...props} arrow={true}>
          <span>Hover Me</span>
      </RdsTooltip>
  },
)
