import React from "react";
import RdsCompAdaptiveCards from "./rds-comp-adaptive-cards";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompAdaptiveCards,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=18411-195150",
  {
    props: {
      showDismiss: figma.boolean("👀Show Dismiss"),
      showHeader: figma.boolean("👀Show Header"),
    },
    example: (props) => (
      <RdsCompAdaptiveCards
        {...props}
        btn1Label="Cancel"
        btn2Label="Done"
        cardTitle="Title"
        showBtn1
        showBtn2
        closeIcon
      />
    ),
  }
);
