import React from "react"
import figma from "@figma/code-connect"
import RdsSearch from "./rds-search"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsSearch,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=52-624",
  {
    props: {
      showHintText: figma.boolean("Show Hint Text"),
      showAsterisk: figma.boolean("Show Asterisk "),
      type: figma.enum("Type", {
        "Left Icon+Text": "left-icon-text",
        "Right Icon + Text": "right-icon---text",
        Type3: "type3",
        Type4: "type4",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
        Large: "large",
      }),
    },
    example: (props) => <RdsSearch  {...props} placeholder={""}/>,
  },
)
