import React from "react"
import figma from "@figma/code-connect"
import RdsStackedChart from "./rds-chart-stacked"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsStackedChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10033-13993",
  {
    props: {
      showThirdDataset: figma.boolean("Show Third Dataset"),
      showGrid: figma.boolean("Show Grid"),
      showSecondDataset: figma.boolean("Show Second Dataset"),
      showLegend: figma.boolean("Show Legend"),
      showFourthDataset: figma.boolean("Show Fourth Dataset"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <RdsStackedChart {...props} labels={[]} options={undefined} dataSets={[]} id={""} />,
  },
)
