import React from "react"
import RdsCompAreaChart from "./rds-comp-chart-area"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompAreaChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10484-3324",
  {
    props: {},
    example: (props) => <RdsCompAreaChart
      {...props}
      dataSets={[
        {
          backgroundColor: () => { },
          borderColor: '#4DCFFF',
          data: [
            600,
            462,
            405,
            362,
            350,
            350.5,
            320.8,
            318,
            605,
            689,
            352,
            354
          ],
          fill: true,
          label: 'Sales',
          pointRadius: 2,
          tension: 0.4
        },
        {
          backgroundColor: () => { },
          borderColor: '#863BFF',
          data: [
            250,
            780.2,
            780.4,
            650,
            455,
            455.5,
            455.8,
            456,
            610,
            455,
            250,
            254
          ],
          fill: true,
          label: 'Revenue',
          pointBackgroundColor: '#863BFF',
          pointRadius: 2,
          tension: 0.4
        }
      ]}
      id="area chart"
      labels={[
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec'
      ]}
      options={{
        borderWidth: 2,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            align: 'end',
            labels: {
              boxHeight: 10,
              boxWidth: 10,
              height: 5,
              padding: 30,
              pointStyleWidth: 13,
              usePointStyle: true
            },
            pointStyle: 'circle',
            position: 'top'
          },
          title: {
            display: false
          },
          tooltip: {
            enabled: true
          }
        },
        pointStyle: 'circle',
        radius: 0,
        responsive: true,
        scales: {
          x: {
            axis: 'x',
            beginAtZero: false,
            border: {
              color: 'rgba(0,0,0,0.1)',
              dash: [],
              dashOffset: 0,
              display: true,
              width: 1
            },
            bounds: 'ticks',
            clip: true,
            display: true,
            grace: 0,
            grid: {
              borderColor: 'rgba(0,0,0,0.1)',
              borderDash: [],
              borderDashOffset: 0,
              borderWidth: 1,
              color: 'rgba(0,0,0,0.1)',
              display: false,
              drawBorder: true,
              drawOnChartArea: true,
              drawTicks: true,
              lineWidth: 1,
              offset: false,
              tickColor: () => { },
              tickLength: 8,
              tickWidth: () => { }
            },
            id: 'x',
            offset: false,
            position: 'bottom',
            reverse: false,
            ticks: {
              align: 'center',
              autoSkip: true,
              autoSkipPadding: 3,
              backdropColor: 'rgba(255, 255, 255, 0.75)',
              backdropPadding: 2,
              callback: () => { },
              color: '#666',
              crossAlign: 'near',
              display: true,
              labelOffset: 0,
              major: {},
              maxRotation: 50,
              minRotation: 0,
              minor: {},
              mirror: false,
              padding: 3,
              showLabelBackdrop: false,
              textStrokeColor: '',
              textStrokeWidth: 0
            },
            title: {
              color: '#666',
              display: false,
              padding: {
                bottom: 4,
                top: 4
              },
              text: ''
            },
            type: 'category'
          },
          y: {
            axis: 'y',
            beginAtZero: true,
            border: {
              color: 'rgba(0,0,0,0.1)',
              dash: [],
              dashOffset: 0,
              display: true,
              width: 1
            },
            bounds: 'ticks',
            clip: true,
            display: true,
            grace: 0,
            grid: {
              borderColor: 'rgba(0,0,0,0.1)',
              borderDash: [],
              borderDashOffset: 0,
              borderWidth: 1,
              color: 'rgba(0,0,0,0.1)',
              display: false,
              drawBorder: true,
              drawOnChartArea: true,
              drawTicks: true,
              lineWidth: 1,
              offset: false,
              tickColor: () => { },
              tickLength: 8,
              tickWidth: () => { }
            },
            id: 'y',
            legend: {
              labels: {
                maxheight: 10
              }
            },
            offset: false,
            position: 'left',
            reverse: false,
            ticks: {
              align: 'center',
              autoSkip: true,
              autoSkipPadding: 3,
              backdropColor: 'rgba(255, 255, 255, 0.75)',
              backdropPadding: 2,
              callback: () => { },
              color: '#666',
              crossAlign: 'near',
              display: true,
              labelOffset: 0,
              major: {},
              maxRotation: 50,
              minRotation: 0,
              minor: {},
              mirror: false,
              padding: 3,
              showLabelBackdrop: false,
              textStrokeColor: '',
              textStrokeWidth: 0
            },
            title: {
              color: '#666',
              display: false,
              padding: {
                bottom: 4,
                top: 4
              },
              text: ''
            },
            type: 'linear'
          }
        },
        tooltip: {
          display: true,
          usePointStyle: true
        }
      }} isGradient={true}  />,
  },
)
