import React from "react"
import  RdsAccordion  from "./rds-accordion"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// Default Layout - no defaultExpanded prop
figma.connect(
  RdsAccordion,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=513-2027",
  {
    variant: { "📱 Layout": "Default" },
    props: {
      ShowLeftIcon: figma.boolean("⬅️ Show Left Icon"),
      title: figma.string("✏️ Title"),
      size: figma.enum("📏 Size", { Small: "small", Medium: "medium", Large: "large" }),
      state: figma.enum("💡 State", { Default: "default", Hover: "hover", Selected: "selected" }),
    },
    example: (props) => (
      <RdsAccordion {...props}
       defaultExpanded={false}
      >
        <span>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget.
        </span>
      </RdsAccordion>
    ),
  }
)

// Expanded Layout - with defaultExpanded prop
figma.connect(
  RdsAccordion,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=513-2027",
  {
    variant: { "📱 Layout": "Expanded" },
    props: {
      ShowLeftIcon: figma.boolean("⬅️ Show Left Icon"),
      title: figma.string("✏️ Title"),
      size: figma.enum("📏 Size", { Small: "small", Medium: "medium", Large: "large" }),
      state: figma.enum("💡 State", { Default: "default", Hover: "hover", Selected: "selected" }),
    },
    example: (props) => (
      <RdsAccordion {...props}
       defaultExpanded={true}
       >
        <span>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget.
        </span>
      </RdsAccordion>
    ),
  }
)
