import React from "react"
import figma from "@figma/code-connect"
import RdsAvatar from "./rds-avatar"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=530-4297",
  {
    props: {
      showNameDesignation: figma.boolean("🔤 Show Name & Designation"),
      changeIcon: figma.instance("🔃 Change Icon"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      activityRing: figma.boolean("⭕ Activity ring"),
      showDesignation: figma.boolean("🔤 Show Designation"),
      subtext: figma.string("✏️ Subtext"),
      title: figma.string("✏️ Title"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      size: figma.enum("📏 Size", {
        Largest: "largest",
        Large: "large",
        Medium: "medium",
        Small: "small",
        Smallest: "smallest",
      }),
      type: figma.enum("⚠️ Type", {
        Image: "image",
        Initials: "initials",
        Icon: "icon",
      }),
      style: figma.enum("✨ Style", {
        "With Name": "with-name",
        "Name On Bottom": "name-on-bottom",
        Stacking: "stacking",
      }),
    },
    example: (props) => <RdsAvatar {...props}/>,
  },
)
