import React from "react"
import figma from "@figma/code-connect"
import RdsAvatar, { AvatarSize, AvatarStyle } from "./rds-avatar"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAvatar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=530-4297",
  {
    props: {
      showNameDesignation: figma.boolean("🔤 Show Name & Designation"),
      activeDotTop: figma.boolean("● Active Dot - Top"),
      activityRing: figma.boolean("⭕ Activity ring"),
      title: figma.string("✏️ Title"),
      activeDotBottom: figma.boolean("● Active Dot - Bottom"),
      size: figma.enum("📏 Size", {
        Largest: AvatarSize.largest,
        Large: AvatarSize.large,
        Medium: AvatarSize.medium,
        Small: AvatarSize.small,
        Smallest: AvatarSize.smallest,
      }),
      type: figma.enum("⚠️ Type", {
        Image: "image",
        Initials: "initials",
        Icon: "icon",
      }),
      style: figma.enum("✨ Style", {
        WithName: AvatarStyle.withname,
        NameOnBottom: AvatarStyle.nameonbottom,
        Stacking: AvatarStyle.stacking,
      }),
    },
    example: (props) => (
      <RdsAvatar
        {...props}
        style={AvatarStyle.withname}
        firstName="Wai"
        lastName="Technologies"
        showName={true}
        colorVariant="primary"
        role="Developer"
        profilePic="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU"
        avatars={[
          {
            profilePic:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU",
          },
          {
            profilePic:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU",
          },
          {
            profilePic:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU",
          },
          {
            profilePic:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU",
          },
          {
            profilePic:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJxA5cTf-5dh5Eusm0puHbvAhOrCRPtckzjA&usqp=CAU",
          },
        ]}
      />
    ),
  }
);
