import React from "react"
import figma from "@figma/code-connect"
import RdsCard from "./rds-card"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCard,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=573-9434",
  {
    props: {
      showIndicator: figma.boolean("👀 Show Indicator"),
      showTitle: figma.boolean("🆕 Show Title"),
      state: figma.enum("💡 State", {
        Default: "Default",
        Hover: "Hovered",
        Selected: "Selected",
        Disabled: "Disabled",
      }),
      style: figma.enum("✨ Style", {
        Default: "Default",
        Outlined: "Outlined",
        Filled: "Filled",
      }),

    },
    example: (props) => <RdsCard 
    {...props}
      borderColor=""
      buttonLabel1="Link Button"
      buttonLabel2="Cancel"
      buttonLabel3="Okay"
      cardSubTitle="Card Sub title"
      cardText="In a laoreet purus. Integer turpis quam, laoreet id orci nec, ultrices lacinia nunc. Aliquam erat vo"
      cardTitle="Card title"
      colorVariant="primary"
      iconName="circle"
      imageUrl="https://picsum.photos/seed/picsum/1200/600"
      layout="Vertical"
      showCardText
      showFooter
      showIcon
      showLinkButton
      showSubTitle
      showTitleAndSubText
     />,
  },
)
