import React from "react"
import figma from "@figma/code-connect"
import RdsAppDetail from "./rds-app-detail"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsAppDetail,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=228-868",
  {
    props: {
      showIcon: figma.boolean("👀 - Show Icon"),
      style: figma.enum("✨ Style", {
        Default: "default",
        Outlined: "outlined",
      }),
    },
    example: (props) => <RdsAppDetail {...props} appDetailsItem={{
      title: "",
      subtitle: "",
      icon: "",
      route: "",
      selected: undefined,
      iconHeight: "",
      iconWidth: "",
      iconFill: false,
      iconColor: "",
      iconStroke: false,
      routeLabel: ""
    }} />,
  },
)
