import React from "react"
import figma from "@figma/code-connect"
import RdsOffcanvas from "./rds-offcanvas"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsOffcanvas,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=1986-8214",
  {
    props: {
      showTertiaryButton: figma.boolean("⏺ Show Tertiary Button"),
      showSecondaryButton: figma.boolean("🔶 Show Secondary Button"),
      showPrimaryButton: figma.boolean("🔷 Show Primary Button"),
    },
    example: (props) => <RdsOffcanvas placement={"start"} backDrop={false} scrolling={false} offId={"offcanvas1"} canvasTitle={"NEW TENENT"}  {...props}/>,
  },
)
