import React from "react"
import figma from "@figma/code-connect"
import RdsBooleanChart from "./rds-chart-boolean"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBooleanChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9923-4213",
  {
    props: {
      showIcon: figma.boolean("Show Icon"),
      iconSwap: figma.instance("Icon Swap"),
      state: figma.enum("💡 State", {
        Default: "default",
        Hover: "hover",
      }),
      level: figma.enum("📏 Level", {
        "25%": "25-",
        "50%": "50-",
        "75%": "75-",
        "100%": "100-",
      }),
    },
    example: (props) => <RdsBooleanChart {...props} labels={[]} options={undefined} dataSets={[]} id={""} />,
  },
)
