import React from "react"
import RdsTextArea, { TextareaState, TextareaStyle } from "./rds-text-area"
import figma from "@figma/code-connect"
import { style } from "wavesurfer.js/src/util"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsTextArea,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1324-14474",
  {
    props: {
      showTitle: figma.boolean("🆕 Show Title"),
      label: figma.string("✏️ Label"),
      state: figma.enum("💡 State", {
        Default : TextareaState.Default,
        Active : TextareaState.Active,
        Selected : TextareaState.Selected,
        Disabled : TextareaState.Disabled,
        Error : TextareaState.Error
      }),
      style: figma.enum("✨ Style", {
        Default : TextareaStyle.Default,
        Pill : TextareaStyle.Pill,
        "Bottom Outline" : TextareaStyle.BottomOutline
      }),
    },
    example: (props) => <RdsTextArea {...props} isMandatory placeholder = "Enter Description" />,
  },
)
