import React from "react"
import figma from "@figma/code-connect"
import RdsScatterChart from "./rds-chart-scatter"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsScatterChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10013-1211",
  {
    props: {
      showScatterDataset: figma.boolean("Show Scatter Dataset"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <RdsScatterChart {...props} labels={[]} options={undefined} dataSets={[]} id={""} />,
  },
)
