
import React from 'react';
import { RdsMultiLevelMenu, MenuOption } from './rds-multi-level-menu';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Elements/Multi Level Menu',
  component: RdsMultiLevelMenu,
  parameters: {
    layout: 'padded',
    // hide these autogenerated controls from the Controls panel
    controls: {
    exclude: ['onSelect'],
    },
  },
  tags: ['autodocs'],
  argTypes: {
    type: {
      control: { type: 'select' },
      options: ['expandable', 'selectable'],
      description: 'Defines the menu behavior, either expandable sub-menus or selectable items',
    },
    size: {
      control: { type: 'select' },
      options: ['default', 'large'],
      description: 'Sets the size of the menu items',
    },
    state: {
      control: { type: 'select' },
      options: ['default', 'hover', 'selected'],
      description: 'Sets the visual state of the menu items',
    },
  },
} satisfies Meta<typeof RdsMultiLevelMenu>;

export default meta;
type Story = StoryObj<typeof RdsMultiLevelMenu>;

const options: MenuOption[] = [
  {
    label: 'Option',
    shortcut: 'Shortcut',
  },
  { label: 'Option', shortcut: 'Shortcut' },
  { label: 'Option', shortcut: 'Shortcut',    children: [
    {
      label: 'Option',
      shortcut: 'Shortcut',
    },
    { label: 'Option', shortcut: 'Shortcut' },
    { label: 'Option', shortcut: 'Shortcut' },
  ], },
  { label: 'Option', shortcut: 'Shortcut' },
  { label: 'Option', shortcut: 'Shortcut' },
  { label: 'Option', shortcut: 'Shortcut' },
];


export const Default:Story ={
   args: {
      options: options,
      type: 'expandable',
      size: 'default',
      state: 'default',
   }
}
