import React from "react"
import RdsMultiLevelMenu from "./rds-multi-level-menu"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsMultiLevelMenu,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=959-2790",
  {
    props: {
      size: figma.enum("📏 Size", {
        Default: "default",
        Large: "large"
      })
    },
    example: (props) => <RdsMultiLevelMenu 
    {...props}
    options={[
    {
      label: 'Option',
      shortcut: 'Shortcut'
    },
    {
      label: 'Option',
      shortcut: 'Shortcut'
    },
    {
      children: [
        {
          label: 'Option',
          shortcut: 'Shortcut'
        },
        {
          label: 'Option',
          shortcut: 'Shortcut'
        },
        {
          label: 'Option',
          shortcut: 'Shortcut'
        }
      ],
      label: 'Option',
      shortcut: 'Shortcut'
    },
    {
      label: 'Option',
      shortcut: 'Shortcut'
    },
    {
      label: 'Option',
      shortcut: 'Shortcut'
    },
    {
      label: 'Option',
      shortcut: 'Shortcut'
    }
  ]}/>,
  },
)
