import React from "react"
import figma from "@figma/code-connect"
import RdsProgressBar from "./rds-progress-bar"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsProgressBar,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=591-8917",
  {
    props: {
      style: figma.enum("✨ Style", {
        Circular: "circular",
        Line: "line",
        Stepper: "stepper",
        Dash: "dash", 
        Block: "block",
      }),
    },
    example: (props) => <RdsProgressBar 
    striped
    height={4}
    role={props.style} 
    steps={4} 
    completedSteps={2} 
    colorVariant="primary"
    displayPercentage 
    progressWidth={40} 
    progressValues={[
      {
        animation: true,
        colorVariant: 'success',
        progressWidth: 50,
        stripe: true
      },
      {
        animation: true,
        colorVariant: 'danger',
        progressWidth: 20,
        stripe: true
      },
      {
        animation: true,
        colorVariant: 'info',
        progressWidth: 30,
        stripe: true
      }
    ]}
     />,
  },
)