import React from "react";
import RdsCompLineChart from "./rds-comp-chart-line";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompLineChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9958-1369",
  {
    props: {
      showLegend: figma.boolean("Show Legend"),
      showMyFirstDataset: figma.boolean("Show My First Dataset"),
    },
    example: (props) => (
      <RdsCompLineChart
        {...props}
        dataSets={[
          {
            backgroundColor: "red",
            borderColor: "rgb(75, 192, 192)",
            data: [65, 59, 80, 81, 56, 55, 40],
            fill: false,
            label: "My First Dataset",
            tension: 0.1,
          },
        ]}
        id="linechart"
        labels={["January", "February", "March", "April", "May", "Jun", "July"]}
        options={{
          aspectRatio: 1,
          interaction: {
            intersect: false,
          },
          maintainAspectRatio: false,
          plugins: {
            filler: {
              propagate: false,
            },
            legend: {
              align: "center",
              labels: {
                generateLabels: () => {},
                usePointStyle: true,
              },
              pointStyle: "bottom",
              position: "top",
            },
            title: {
              display: true,
              text: "Line Chart with boundries",
            },
            tooltip: {
              usePointStyle: true,
            },
          },
          pointStyle: "star",
          radius: 7,
          responsive: true,
          scales: {
            x: {
              axis: "x",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: () => {},
                tickLength: 8,
                tickWidth: () => {},
              },
              id: "x",
              offset: false,
              position: "bottom",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                minor: {},
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "category",
            },
            y: {
              axis: "y",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: () => {},
                tickLength: 8,
                tickWidth: () => {},
              },
              id: "y",
              offset: false,
              position: "left",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                minor: {},
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "linear",
            },
          },
        }}
      />
    ),
  }
);
