import React from "react"
import figma from "@figma/code-connect"
import RdsDropdownList, { DropdownSize, DropdownState, DropdownStyle } from "./rds-dropdown-list"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDropdownList,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=450-4389",
  {
    props: {
      showIcon: figma.boolean("👀 Show Icon"),
      showHint: figma.boolean("🔤 Show Hint Text"),
      showTitle: figma.boolean("🆕 Show Title"),
      //hint: figma.string("✏️ Hint "),
      //title: figma.string("✏️ Title "),
      isMandatory: figma.boolean("❗ Is Mandatory"),
      //placeholder: figma.string("✏️ Placeholder "),
      size: figma.enum("📏 Size", {
        Default: DropdownSize.Default,
        Small: DropdownSize.Small,
        Large: DropdownSize.Large,
      }),
      state: figma.enum("💡 State", {
        Default: DropdownState.Default,
        Expanded: DropdownState.Expanded,
        Selected: DropdownState.Selected,
        Disabled: DropdownState.Disabled,
      }),
      style: figma.enum("✨ Style", {
        Default: DropdownStyle.Default,
        "Bottom Line": DropdownStyle.BottomLine,
      }),
    },
    example: (props: any) => <RdsDropdownList  {...props} 
    borderDropdown
    hint="Hint Text"
    icon="dropdown_icon"
    iconHeight="1px"
    iconWidth="1px"
    isPlaceholder
    placeholder="Filter"
    title="Label"
    listItems={[
      {
        icon: 'us',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'EN(US)',
        val: 'en'
      },
      {
        icon: 'in',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'English(IND)',
        val: 'en'
      },
      {
        icon: 'fr',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'Français',
        val: 'fr'
      },
      {
        icon: 'de',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'Deutsch',
        val: 'de'
      },
      {
        icon: 'br',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'Português (Brasil)',
        val: 'pt-BR'
      },
      {
        icon: 'tr',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'Türkçe',
        val: 'tr'
      },
      {
        icon: 'it',
        iconHeight: '20px',
        iconWidth: '20px',
        label: 'Italiano',
        val: 'it'
      }
    ]}/>,
  },
)

