import React from "react"
import figma from "@figma/code-connect"
import RdsToggle, { ToggleLayout, ToggleState, ToggleStyle } from "./rds-toggle"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsToggle,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=720-54963",
  {
    props: {
      showLabel: figma.boolean("📝 - Label Text"),
      label: figma.string("✏️ Text / Title"),
      layout: figma.enum("📱 Layout", {
        "Switch + Label": ToggleLayout.SwitchLabel,
      "Label + Switch": ToggleLayout.LabelSwitch,
      "Top Lable + Switch": ToggleLayout.TopLabelSwitch,
      "Bottom Lable + Switch": ToggleLayout.BottomLabelSwitch
    }),
      
      state: figma.enum("💡 State", {
        Off: ToggleState.Off,
        On: ToggleState.On,
        DisabledOn: ToggleState.DisabledOn,
        DisabledOff: ToggleState.DisabledOff,
      }),
      style: figma.enum("✨ Style", {
        "Style 1": ToggleStyle.Style1,
        "Style 2": ToggleStyle.Style2,
        "Style 3": ToggleStyle.Style3,
        "Style 4": ToggleStyle.Style4,
        "Style 5": ToggleStyle.Style5,
        "Style 6": ToggleStyle.Style6,
      }),
    },
    example: (props) => <RdsToggle
    {...props}
    checked={false}
/>

  },
)
