import React from "react"
import figma from "@figma/code-connect"
import RdsToggle from "./rds-toggle"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsToggle,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=720-54963",
  {
    props: {
      labelText: figma.boolean("📝 - Label Text"),
      textTitle: figma.string("✏️ Text / Title"),
      layout: figma.enum("📱 Layout", {
        "Switch + label": "Switch + label",
        "label + Switch": "label + Switch",
        "Top label + Switch": "Top label + Switch",
        "Bottom label + Switch": "Bottom label + Switch",
      }),
      
      
      state: figma.enum("💡 State", {
        Off: "off",
        On: "on",
        "Disabled On": "disabled-on",
        "Disabled Off": "disabled-off",
      }),
      style: figma.enum("✨ Style", {
        "Style 1": "Style 1",
        "Style 2": "Style 2",
        "Style 3": "Style 3",
        "Style 4": "Style 4",
        "Style 5": "Style 5",
        "Style 6": "Style 6",
      }),
    },
    example: (props) => <RdsToggle
    {...props}
    checked={false}
  />

  },
)
