import React from "react"
import  RdsCompOffcanvas, { RdsOffcanvasBackDrop, RdsOffcanvasPlacement }  from "./rds-comp-off-canvas"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompOffcanvas,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1986-8214",
  {
    props: {
      showPrimaryButton: figma.boolean("🔷 Show Primary Button"),
      showSecondaryButton: figma.boolean("🔶 Show Secondary Button"),
      showTertiaryButton: figma.boolean("⏺ Show Tertiary Button"),
    },
    example: (props) => <RdsCompOffcanvas 
    {...props}
    placement={RdsOffcanvasPlacement.End} 
    backDrop={RdsOffcanvasBackDrop.Static} 
    offcanvaswidth={650}
    canvasTitle="NEW TENANT"
    offId="canvasExample"
    />,
  },
)
