import React from "react";
import RdsCompScatterChart from "./rds-comp-chart-scatter";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompScatterChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10013-1211",
  {
    props: {
      showScatterDataset: figma.boolean("Show Scatter Dataset"),
    },
    example: (props) => (
      <RdsCompScatterChart
        dataSets={[
          {
            backgroundColor: "rgb(255, 99, 132)",
            data: [
              {
                x: -10,
                y: 0,
              },
              {
                x: -8,
                y: 3,
              },
              {
                x: -5,
                y: 5,
              },
              {
                x: 0,
                y: 9,
              },
              {
                x: 4,
                y: 3,
              },
              {
                x: 9,
                y: 5,
              },
              {
                x: 0.5,
                y: 5.5,
              },
            ],
            label: "Scatter Dataset",
            pointRadius: 8,
            pointStyle: "triangle",
            type: "scatter",
          },
        ]}
        id="Scatter_Chart"
        labels={["January", "February", "March", "April"]}
        options={{
          maintainAspectRatio: false,
          plugins: {
            legend: {
              align: "center",
              labels: {
                usePointStyle: true,
              },
              position: "top",
            },
            tooltip: {
              usePointStyle: true,
            },
          },
          responsive: true,
          scales: {
            x: {
              axis: "x",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: true,
                tickColor: "#666",
                tickLength: 8,
                tickWidth: 1,
              },
              offset: true,
              position: "bottom",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                // callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "linear",
            },
            y: {
              axis: "y",
              beginAtZero: false,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: "#666",
                tickLength: 8,
                tickWidth: 1,
              },
              offset: false,
              position: "left",
              reverse: false,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                //callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                mirror: false,
                padding: 3,
                showLabelBackdrop: false,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "linear",
            },
          },
        }}
      />
    ),
  }
);
