import React from "react"
import RdsEmojiGenerator, { EmojiCategory, EmojiGeneratorType, SkinToneState } from "./rds-comp-emoji-generator"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsEmojiGenerator,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9141-36081",
  {
    props: {
      // showSkinTone: figma.boolean("showSkinTone"),
      // showFooter: figma.boolean("showFooter"),
      Type: figma.enum("Type", {
        "Default": EmojiGeneratorType.Default,
        "Quick Reactions": EmojiGeneratorType.QuickReactions,
      }),
      // category: figma.enum("Category", {
      //   "SmileysAndPeople": EmojiCategory.SmileysAndPeople,
      //   "AnimalsAndNature": EmojiCategory.AnimalsAndNature,
      //   "FoodAndDrink": EmojiCategory.FoodAndDrink,
      //   "TravelAndPlaces": EmojiCategory.TravelAndPlaces,
      //   "Activities": EmojiCategory.Activities,
      //   "Objects": EmojiCategory.Objects,
      //   "Symbols": EmojiCategory.Symbols,
      //   "Flags": EmojiCategory.Flags,
      // }),
      // State: figma.enum("State", {
      //   "Expanded": SkinToneState.Expanded,
      //   "Default": SkinToneState.Default,
      // }),
    },
    example: (props) => (
      <RdsEmojiGenerator
        {...props}
        maxEmojis={100}
      />
    ),
  },
)
