import React from "react"
import figma from "@figma/code-connect"
import RdsCompAddressDetail from "./rds-comp-address-detail"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompAddressDetail,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=19-18",
  {
    props: {
      showTitle: figma.boolean("🆕 Show Title"),
      showIcon: figma.boolean("👀 - Show Icon"),
      style: figma.enum("✨ Style", {
        Default: "default",
        Outlined: "outlined",
      }),
      level: figma.enum("📊 Level", {
        "Level 1": "level-1",
        "Level 2": "level-2",
        "Level 3": "level-3",
      }),
    },
    example: (props: any) => <RdsCompAddressDetail {...props} children={undefined} />,
  },
)

