import React from "react"
import figma from "@figma/code-connect"
import RdsPieChart from "./rds-chart-pie"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPieChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10057-1579",
  {
    props: {
      level: figma.enum("Level", {
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "1": "1",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <RdsPieChart {...props} labels={[]} options={undefined} dataSets={[]} radius={0} id={""} />,
  },
)
