import React from "react";
import RdsCompGaugeChart from "./rds-comp-chart-gauge";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompGaugeChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=15590-3864",
  {
    props: {},
    example: (props) => (
      <RdsCompGaugeChart
        dataSets={[
          {
            backgroundColor: [
              "#28a745",
              "#17a2b8",
              "#ffc107",
              "#fd7e14",
              "#6f42c1",
              "#dc3545",
            ],
            borderWidth: 0,
            cutout: "70%",
            data: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
            label: "Gauge Data",
          },
        ]}
        id="gaugeChart"
        labels={["Green", "Blue", "Yellow", "Orange", "Purple", "Red"]}
        options={{
          maintainAspectRatio: false,
          plugins: {
            legend: {
              display: true,
              position: "top",
            },
            tooltip: {
              enabled: true,
            },
          },
        }}
        subTitleText="Subtitle"
        titleText="Title"
      />
    ),
  }
);
