import React from "react"
import  RdsCompProductTour  from "./rds-comp-product-tour"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompProductTour,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=18451-13553",
  {
    props: {
      bottomLeft: figma.boolean("Bottom Left Dot"),
      bottomRight: figma.boolean("Bottom Right Dot"),
      topRight: figma.boolean("Top Right Dot"),
      topLeft: figma.boolean("Top Left Dot"),
      description: figma.string("✍ Description"),
      header: figma.string("Header"),
      showPrimaryButton: figma.boolean("🔷 Primary Button"),
      showSecondaryButton: figma.boolean("🔶 Secondary Button"),
      showTertiaryButton: figma.boolean("⏺ Tertiary Button"),
      stepsIndicator: figma.string("Steps Indicator"),
      showVisualPlaceholder: figma.boolean("Show Visual Placeholder"),
      showDismiss: figma.boolean("Show Dismiss"),
      state: figma.enum("💡 State", {
      "With Image": "Image",
      "With Carousal": "Carousel",
      "With GIF": "GIF",
      "With Form": "Form",
    }),
    },
    
    example: (props) => <RdsCompProductTour {...props} />,
  },
)
