import React from "react"
import figma from "@figma/code-connect"
import RdsCompDatatable, { ActionPosition } from "./rds-comp-data-table"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompDatatable,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1601-16775",
  {
    props: {
      state: figma.enum("💡 State", {
        Default: "default",
      }),
    },
    example: (props) => <RdsCompDatatable 
    actionPosition={ActionPosition.Left}
  actions={[
    {
      displayName: 'Delete',
      id: 'delete'
    },
    {
      displayName: 'Edit',
      id: 'edit'
    }
  ]}
  enableRadioButtonselection
  enablecheckboxselection
  isClickable
  pagination
  recordsPerPage={10}
  tableData={[
    {
        avatar: {
            name: "John Doe",
            src: "avatar1.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 1",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 1,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "active",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "pending",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    },
    {
        avatar: {
            name: "Jane Doe",
            src: "avatar2.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 2",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 2,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "active",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "pending",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    },
    {
        avatar: {
            name: "Jim Doe",
            src: "avatar3.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 3",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 3,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "inactive",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "error",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    },
    {
        avatar: {
            name: "John Doe",
            src: "avatar1.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 1",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 4,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "active",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "pending",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    },
    {
        avatar: {
            name: "Jane Doe",
            src: "avatar2.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 2",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 5,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "active",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "pending",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    },
    {
        avatar: {
            name: "Jim Doe",
            src: "avatar3.jpg",
        },
        badge: {
            badgeColorVariant: "primary",
            content: "badge 3",
            icon: "iconName",
        },
        checkbox: " Text ",
        checkboxBadges: [
            {
                badgeColorVariant: "primary",
                content: "badge 1",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "badge 2",
                icon: "iconName",
            },
        ],
        edition: "Text",
        id: 6,
        member: "Joy",
        progressBar: "Text",
        sampleText: "This is a sample text",
        status: " Text ",
        statusBadges: [
            {
                badgeColorVariant: "primary",
                content: "inactive",
                icon: "iconName",
            },
            {
                badgeColorVariant: "primary",
                content: "error",
                icon: "iconName",
            },
        ],
        tenant: "Text",
        text: " text ",
        userName: "iconAvatarTitle",
    }
]}
  tableHeaders={[
    {
      dataLength: 50,
      datatype: 'text',
      displayName: 'Text',
      key: 'text',
      required: false
    },
    {
      dataLength: 30,
      datatype: 'text',
      displayName: 'Text',
      fontWeight: 'medium',
      isBold: true,
      key: 'tenant',
      required: true,
      sortable: true
    },
    {
      dataLength: 30,
      datatype: 'avatarTitleInfo',
      displayName: 'Text',
      key: 'member',
      required: true,
      sortable: true
    },
    {
      dataLength: 50,
      datatype: 'text',
      displayName: 'Text',
      key: 'sampleText',
      required: false
    },
    {
      dataLength: 30,
      datatype: 'text',
      displayName: 'Text',
      key: 'edition',
      required: true,
      sortable: true
    },
    {
      dataLength: 50,
      datatype: 'progressbar',
      displayName: 'Text',
      key: 'progressBar',
      required: false
    },
    {
      dataLength: 5,
      datatype: 'status',
      displayName: 'Text',
      key: 'status',
      required: true
    },
    {
      datatype: 'iconAvatarTitle',
      displayName: 'Text',
      key: 'userName',
      sortable: true
    },
    {
      dataLength: 5,
      datatype: 'checkbox',
      displayName: 'Text',
      key: 'checkbox',
      required: false
    }
  ]}
   />,
  },
)
