import React from "react"
import figma from "@figma/code-connect"
import RdsButton from "./rds-button"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsButton,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=219-1317",
  {
    props: {
      text: figma.string("✏️ Text"),
      changeIcon: figma.instance("🔃 Change Icon"),
      size: figma.enum("📏 Size", {
        Large: "large",
        Medium: "medium",
        Small: "small",
      }),
      shape: figma.enum("💠 Shape", {
        Pill: "pill",
        Rectangle: "rectangle",
      }),
      state: figma.enum("💡 State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
        Selected: "selected",
      }),
      layout: figma.enum("📱 Layout", {
        "Icon+Text": "icon-text",
        "Icon Only": "icon-only",
        "Text Only": "text-only",
      }),
      style: figma.enum("✨ Style", {
        Filled: "filled",
        Outline: "outline",
        Transparent: "transparent",
      }),
    },
    example: (props) => <RdsButton {...props}/>,
  },
)
