import React from "react"
import figma from "@figma/code-connect"
import RdsButton from "./rds-button"
import { TooltipStyle } from "../rds-tooltip/rds-tooltip"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsButton,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=219-1317",
  {
    props: {
      size: figma.enum("📏 Size", {
        Large: "large",
        Medium: "medium",
        Small: "small",
      }),
      shape: figma.enum("💠 Shape", {
        Pill: "pill",
        Rectangle: "rectangle",
      }),
      state: figma.enum("💡 State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
        Selected: "selected",
      }),
      badgeLayout: figma.enum("📱 Layout", {
        "Icon+Text": "Icon + Text",
        "Icon+Only": "Icon + Only",
        "Text+Only": "Text + Only",
      }),
      style: figma.enum("✨ Style", {
        Filled: "filled",
        Outline: "outline",
        Transparent: "transparent",
      }),
    },
    example: (props: any) => <RdsButton {...props}
    badgeState={props.state}
    badgeStyle="primary"
    colorVariant="primary"
    databstoggle="tooltip"
    displayType={props.badgeLayout}
    icon="circle"
    label="Click Here"
    textCase="unset"
    tooltipPlacement={TooltipStyle.LeftArrow}
    tooltipTitle="This is tooltip"
    />,
  },
)

