import React from "react"
import figma from "@figma/code-connect"
import RdsCompGrid from "./rds-comp-grid"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompGrid,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=3059-23557",
  {
    props: {
      state: figma.enum("💡 State", {
        Default: "default",
      }),
    },
    example: (props) => <RdsCompGrid {...props} tableHeaders={[]} tableData={[]} pagination={false} />,
  },
)
