import React from "react"
import figma from "@figma/code-connect"
import RdsStepper from "./rds-stepper"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsStepper,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=666-2576",
  {
    props: {
      level: figma.enum("📊 Level", {
        "Level 1": "level-1",
        "Level 2": "level-2",
        "Level 3": "level-3",
        "Level 4": "level-4",
        "Level 5": "level-5",
      }),
    },
    example: (props) => <RdsStepper {...props} detail={undefined} />,
  },
)
