import React from "react"
import  RdsCompLayout  from "./rds-comp-layout"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompLayout,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=2799-7589",
  {
    props: {
      displayType:figma.enum("💡 State",{
        "Basic":"Basic",
        'Board':'Board',
        'Boxify':'Boxify',
        'Cardify':'Cardify',
        'Collage':'Collage',
        'Gridify':'Gridify',
        'Highlight':'Highlight',
        'Matrix':'Matrix',
        'Mosaic':'Mosaic',
        'Nexus':'Nexus',
        'Pinboard':'Pinboard',
        'Sections':'Sections',
        'Snapshots':'Snapshots',
        'Splitz':'Splitz',
        'Spotlight':'Spotlight',
        'Stacks':'Stacks',
        'Dashboard':'Dashboard',
        'Relaxed':'Relaxed'

      }),
    },
    example: (props) => <RdsCompLayout mode="standard" {...props} />,
  },
)
