import React from "react"
import  RdsGrid  from "./rds-comp-grid"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsGrid,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=16112-91459",
  {
    props: {
      showAddNewRow: figma.boolean("👀 Show Add New Row"),
      showSubHeader: figma.boolean("👀 Show Sub Header"),
      showHeader: figma.boolean("👀 Show Header"),
    },
    example: (props) => <RdsGrid tableHeaders={[]} tableData={[]} />,
  },
)
