import React from "react"
import  RdsMenu  from "./rds-menu"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsMenu,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=959-2790",
  {
    props: {
      size: figma.enum("📏 Size",  {
        "Default": "small",
        "Large": "large"
      }),
    },
    example: (props) => <RdsMenu  
    {...props}
    items={[
              {
                id: 1,
                label: 'Profile'
              },
              {
                id: 2,
                label: 'My account'
              },
              {
                id: 3,
                label: 'Logout'
              }
        ]} 
  open={true} />,
  },
)
