import React from "react"
import RdsCompRadarChart from "./rds-comp-chart-radar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompRadarChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10004-2478",
  {
    props: {
      showDataset2: figma.boolean("Show Dataset 2"),
      showYAxisData: figma.boolean("Show Y Axis Data"),
      showLegend: figma.boolean("Show Legend"),
      showDataset1: figma.boolean("Show Dataset 1"),
      showDataset3: figma.boolean("Show Dataset 3"),
    },
    example: (props) => <RdsCompRadarChart
  dataSets={[
    {
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)'
      ],
      borderColor: [
        '#ff9f40'
      ],
      data: [
        0.5,
        0.8,
        0.4,
        0.6,
        0.7,
        0.2,
        0.9
      ],
      fill: false,
      label: 'Dataset 1',
      pointRadius: 2,
      pointStyle: 'circle'
    },
    {
      backgroundColor: [
        'rgba(255, 206, 86, 0.2)'
      ],
      borderColor: [
        '#ff6384'
      ],
      data: [
        0.9,
        0.3,
        0.8,
        0.9,
        0.1,
        0.7,
        0.2
      ],
      fill: true,
      label: 'Dataset 2',
      pointRadius: 2,
      pointStyle: 'circle'
    },
    {
      backgroundColor: [
        'rgba(255, 240, 204, 0.2)'
      ],
      borderColor: [
        '#83BE5A'
      ],
      data: [
        0.7,
        0.2,
        0.1,
        0.9,
        0.8,
        0.4,
        0.7
      ],
      fill: false,
      label: 'Dataset 3',
      pointRadius: 2,
      pointStyle: 'circle'
    }
  ]}
  id="Radar_Chart"
  labels={[
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'June',
    'July'
  ]}
  options={{
    chartArea: {
      backgroundColor: 'rgba(251, 85, 85, 0.4)'
    },
    plugins: {
      legend: {
        align: 'start',
        labels: {
          boxHeight: 10,
          boxWidth: 10,
          height: 5,
          padding: 30,
          pointStyleWidth: 13,
          usePointStyle: true
        },
        pointRadius: 5,
        pointStyle: 'rectRot',
        position: 'left'
      },
      scale: {
        angleLines: {
          display: true
        },
        type: 'line'
      },
      title: {
        display: true,
        text: 'Radar Chart'
      },
      tooltip: {
        usePointStyle: true
      }
    },
    responsive: false,
    scales: {
      r: {
        angleLines: {
          borderDash: [],
          borderDashOffset: 0,
          color: 'rgba(0,0,0,0.1)',
          display: true,
          lineWidth: 1
        },
        animate: true,
        axis: 'r',
        beginAtZero: false,
        border: {
          color: 'rgba(0,0,0,0.1)',
          dash: [],
          dashOffset: 0,
          display: true,
          width: 1
        },
        bounds: 'ticks',
        clip: true,
        display: true,
        grace: 0,
        grid: {
          borderColor: 'rgba(0,0,0,0.1)',
          borderDash: [],
          borderDashOffset: 0,
          borderWidth: 1,
          circular: false,
          color: 'rgba(0,0,0,0.1)',
          display: true,
          drawBorder: true,
          drawOnChartArea: true,
          drawTicks: true,
          lineWidth: 1,
          offset: false,
          tickColor: () => {},
          tickLength: 8,
          tickWidth: () => {}
        },
        id: 'r',
        offset: false,
        pointLabels: {
          backdropColor: undefined,
          backdropPadding: 2,
          callback: () => {},
          centerPointLabels: false,
          color: '#666',
          display: true,
          font: {
            size: 10
          },
          padding: 5
        },
        position: 'chartArea',
        reverse: false,
        startAngle: 0,
        ticks: {
          align: 'center',
          autoSkip: true,
          autoSkipPadding: 3,
          backdropColor: 'rgba(255, 255, 255, 0.75)',
          backdropPadding: 2,
          callback: () => {},
          color: '#666',
          crossAlign: 'near',
          display: true,
          labelOffset: 0,
          major: {},
          maxRotation: 50,
          minRotation: 0,
          minor: {},
          mirror: false,
          padding: 3,
          showLabelBackdrop: true,
          textStrokeColor: '',
          textStrokeWidth: 0
        },
        title: {
          color: '#666',
          display: false,
          padding: {
            bottom: 4,
            top: 4
          },
          text: ''
        },
        type: 'radialLinear'
      }
    }
  }}
  {...props}
/>,
  },
)
