import React from "react"
import RdsCompDetailsPane from "./rds-comp-details-pane"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompDetailsPane,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=8157-22064",
  {
    props: {
      style:figma.enum("✨ Style",{
        "Favourites": "Favourites",
        "Favourites - New Folder": "Favourites - New Folder",
        "Prompt History": "Prompt History",
        "Real Estate": "Real Estate",
        "Selection": "Selection",
        "Toolbar": "Toolbar",
        "Thumbnail VIew": "Thumbnail View"
      })
    },
    example: (props) => <RdsCompDetailsPane {...props} 
    addtofolder="Add to Folder"
    addtoscreen="Add to Screen"
    carouselImages={[{
        alt: 'Night Sky',
        src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80'
      },
      {
        alt: 'Night Sky',
        src: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=80'
      },
      {
        alt: 'Night Sky',
        src: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80'
      }
    ]}
    estateDescription="This studio room is located in Major city. The famous Amazon and Amazonia beaches are approximately 10 minutes walk from here. The room has a kitchenette with basic utensils for cooking. There is a private attached bathroom. We have a smart tv for your entertainment. We provide complimentary Wi-Fi to our guests who also want to work."
    estateTitle="Serene Studio Housing"
    favouritesTabLabel="Favourites"
    headerText="My Activity"
    historyTabLabel="History" />,
    },
)
