import React from "react"
import figma from "@figma/code-connect"
import RdsSlider from "./rds-slider"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsSlider,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=867-10909",
  {
    props: {
      rightLabel: figma.string("➡️ Right Label"),
      leftLabel: figma.string("⬅️ Left Label"),
      showLabel: figma.boolean("📝 Show label"),
      type: figma.enum("⚠️ Type", {
        "One Way": "One Way",
        "Two Way": "Two Way",
      }),
    },
    example: (props) => <RdsSlider {...props}/>,
  },
)
