import React from "react"
import figma from "@figma/code-connect"
import RdsRadarChart from "./rds-chart-radar"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsRadarChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=10004-2478",
  {
    props: {
      showDataset1: figma.boolean("Show Dataset 1"),
      showLegend: figma.boolean("Show Legend"),
      showYAxisData: figma.boolean("Show Y Axis Data"),
      showDataset3: figma.boolean("Show Dataset 3"),
      showDataset2: figma.boolean("Show Dataset 2"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
      side: figma.enum("Side", {
        "7": "7",
      }),
    },
    example: (props) => <RdsRadarChart {...props} labels={[]} options={undefined} dataSets={[]} id={""} />,
  },
)
