import React from "react";
import figma from "@figma/code-connect";
import RdsCompReviews, { RevieweStyle, VariantType } from "./rds-comp-reviews";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompReviews,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=901-23708",
  {
    props: {
      name: figma.string("✏️ Name"),
      style: figma.enum("✨ Style", {
        "Style 1": RevieweStyle.Style1,
        "Style 2": RevieweStyle.Style2,
        "Style 3": RevieweStyle.Style3,
        "Style 4": RevieweStyle.Style4,
        "Style 5": RevieweStyle.Style5,
        "Style 6": RevieweStyle.Style6,
        "Style 7": RevieweStyle.Style7,
        "Style 8": RevieweStyle.Style8,
        "Style 9": RevieweStyle.Style9,
        "Style 10": RevieweStyle.Style10,
        "Style 11": RevieweStyle.Style11,
        "Style 12": RevieweStyle.Style12,
        "Style 13": RevieweStyle.Style13,
      }),
    },
    example: (props) => (
      <RdsCompReviews
        {...props}
        variantType={VariantType.Default}
        itemList={[
          {
            name: "Jane Doe",
            username: "Software Developer",
            date: new Date(),
            feedIcon: "person",
            imageUrl:
              "https://th.bing.com/th/id/OIP.3IsXMskZyheEWqtE3Dr7JwHaGe?pid=ImgDet&rs=1",
            description: "Awesome website and funnel for your business",
            hashtags: "#newbag #fancybag #designerbag",
            reviews: "4.75",
            rating: 1,
          },
        ]}
      />
    ),
  }
);
