import React from "react"
import figma from "@figma/code-connect"
import RdsIconLabel from "./rds-icon-label"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsIconLabel,
  "https://www.figma.com/design/wGW5jiXyoAdO4DVLgCKXmw/Raaghu-Storybook-Elements?node-id=50-580",
  {
    props: {
      layout: figma.enum("Layout", {
        "Left Icon+Text": "left-icon-text",
        "Top Icon+Text": "top-icon-text",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      type: figma.enum("Type", {
        Error: "error",
        Primary: "primary",
        Secondary: "secondary",
        Success: "success",
        Info: "info",
        Warning: "warning",
      }),
    },
    example: (props) => <RdsIconLabel {...props}   />,
  },
)
