import React from "react"
import  RdsCard  from "./rds-card"
import figma from "@figma/code-connect"
import { style } from "wavesurfer.js/src/util"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCard,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=573-9434",
  {
    props: {
      showTitle: figma.boolean("🆕 Show Title"),
      showIndicator: figma.boolean("👀 Show Indicator"),
      // cardContent: figma.instance("Card content: .Widgets - Card Content"),
      style: figma.enum("✨ Style", {
        "Default": "default",
        "Outlined": "outlined",
        "Filled": "filled",
      }),
      state: figma.enum("💡 State", {
        "Default": "default",
        "Hover": "hover",
        "Selected": "selected",
        "Disabled": "disabled",
      }),
    },
    example: (props) => <RdsCard {...props}/>,
  },
)
