import React from "react"
import figma from "@figma/code-connect"
import RdsBreadcrumb, { BreadcrumbLevel, BreadcrumbStyle } from "./rds-breadcrumb"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBreadcrumb,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=382-3922",
  {
    props: {
      style: figma.enum("✨ Style", {
        "Without Background": BreadcrumbStyle.WithoutBackground,
        "Square Background": BreadcrumbStyle.SquareBackground,
        "Pill Background": BreadcrumbStyle.PillBackground,
      }),
      level: figma.enum("📊 Level", {
        "Level 1": BreadcrumbLevel.Level1,
        "Level 2": BreadcrumbLevel.Level2,
        "Level 3": BreadcrumbLevel.Level3,
        "Level 4": BreadcrumbLevel.Level4,
        "Level 5": BreadcrumbLevel.Level5,
      }),
      breadcrumbItems: [
        { label: "Home", href: "/" }
      ],
    },
    example: (props) => <RdsBreadcrumb {...props} />,
  }
);
