import React from "react"
import  RdsCompTruncateText  from "./rds-comp-truncate-text"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompTruncateText,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=998-59",
  {
    props: {
      state: figma.enum("💡 State", {
        "Default": "Default",
        "Hover": "Hover",
      }),
    },
    example: (props) => <RdsCompTruncateText 
    text={"This is a sample text"} 
    maxLength={16} 
    state={props.state} />,
  },
)
