import React from "react"
import figma from "@figma/code-connect"
import RdsRadioButton, { RdsRadioButtonLayout, RdsRadioButtonState } from "./rds-radio-button"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsRadioButton,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=346-3467",
  {
    props: {
      text: figma.string("✏️Text"),
      layout: figma.enum("📱 Layout", {
        Icon: RdsRadioButtonLayout.Icon,
        "Icon with Label": RdsRadioButtonLayout.IconWithLabel,
        "Icon with bottom Label": RdsRadioButtonLayout.IconWithBottomLabel,
      }),
      state: figma.enum("💡 State", {
        Default: RdsRadioButtonState.Default,
        Hover: RdsRadioButtonState.Hover,
        Disabled: RdsRadioButtonState.Disabled,
      }),
      selected: figma.boolean("⚠️ Selected"),
    },
    example: (props) => <RdsRadioButton {...props} itemList={undefined} value={""} />,
  },
)
