import React from "react"
import  RdsRange  from "./rds-range"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// One Way - no value prop
figma.connect(
  RdsRange,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=867-10909",
  {
    variant: { "⚠️ Type": "One Way" },
    props: {
      showLabel: figma.boolean("📝 Show label"),
    },
    example: ({ showLabel }) => <RdsRange showLabel={showLabel} type="one-way" />,
  }
)

// Two Way - with value prop
figma.connect(
  RdsRange,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=867-10909",
  {
    variant: { "⚠️ Type": "Two Way" },
    props: {
      showLabel: figma.boolean("📝 Show label"),
    },
    example: ({ showLabel }) => <RdsRange showTooltip={false} showLabel={showLabel} type="two-way" value={[0, 20]} />,
  }
)

