import React from "react"
import  RdsDatepicker, { DatePickerLayout, DatePickerState, DatePickerStyleType }  from "./rds-comp-datepicker"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsDatepicker,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=443-15972",
  {
    props: {
      isMandatory: figma.boolean("❗ - Is Mandatory"),
      showTitle: figma.boolean("🆕 - Show Title"),
      placeholderText: figma.string("✏️ Placeholder Text"),
      // titleText: figma.string("✏️ Title Text: Select Date"),
      //changeIcon: figma.string("🔃 Change Icon"),
      state: figma.enum("💡 State", {
        Default: DatePickerState.Default,
        Expanded: DatePickerState.Expanded,
        Selected: DatePickerState.Selected,
      }),
      datePickerStyleType: figma.enum("⚠️ Type", {
        Default: DatePickerStyleType.Dropdown,
        Selector: DatePickerStyleType.Selector,
      }),

      type: figma.enum("⚠️ Type", {
        Default: "Default",
        Custom: "Custom",
      })
    },
    example: (props) =>  <RdsDatepicker 
    titleText="Select Date"
    isDropdownOpen={false} 
    layout={DatePickerLayout.Default}
    {...props} 
    changeIcon="calendar" 
    />,
  },
)
