import React from "react"
import  RdsCompEmptyState  from "./rds-comp-empty-state"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompEmptyState,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=2155-3061",
  {
    props: {
      mode:figma.enum("🌙 Mode",{
        "Light NRA": "Light NRA",
        "Dark NRA": "Dark NRA"
      })
    },
    example: (props) => <RdsCompEmptyState 
        mode={props.mode}
        buttonText="Add New Data"
        iconHeight={150}
        iconWidth={150}
        label="No Data Available"
        subLabel="No data available at this moment. Would you like to add new data?"
      />,
  },
)
