import React from "react";
import RdsPopover from "./rds-popover";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsPopover,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1509-4672",
  {
    props: {
      position: figma.enum("💡 State", {
        "Top Left": "bottom-left",
        "Top Center": "top-center",
        "Top Right": "bottom-right",
        "Bottom Left": "top-left",
        "Bottom Center": "top-center",
        "Bottom Right": "top-right",
        "Left Top": "right-top",
        "Left Center": "right-center",
        "Left Bottom": "right-bottom",
        "Right Bottom": "left-bottom",
        "Right Center": "left-center",
        "Right Top": "left-top",
        "No Arrow": "no-arrow",
      }),
    },
    example: (props) => (
      <span>
        <span onClick={() => {}}>Open Popover</span>
        <RdsPopover
          {...props}
          isOpen={true}
          anchorEl={null}
          onClose={() => {}}
          title="Simple Popover"
        >
          <span>This is a simple popover with some basic content.</span>
        </RdsPopover>
      </span>
    ),
  }
);
