import React from "react"
import  RdsBreadcrumbs, { BreadcrumbSeparator }  from "./rds-breadcrumbs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBreadcrumbs,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=382-3922",
  {
   // variant: { "📊 Level": "Level 5" },
    props: {
      layout: figma.enum("✨ Style", {
        "Pill Background": "pill background",
        "Square Background": "square background",
        "Without Background": "without background"
      }),
      level: figma.enum("📊 Level", {
        "Level 1": "level1",
        "Level 2": "level2",
        "Level 3": "level3",
        "Level 4": "level4",
        "Level 5": "level5",
      }),
    },
    example: (props) => (
      <RdsBreadcrumbs
        {...props}
        separator={BreadcrumbSeparator.GreaterThan}
        showIcon={true}
        icon="home"
        state="hover"
        items={[
          {
            href: '/',
            label: 'Home'
          },
          {
            href: '/products',
            label: 'Products'
          },
          {
            href: '/products/category',
            label: 'Category'
          },
          {
            href: '/products/category/subcategory',
            label: 'Subcategory'
          },
          {
            active: true,
            label: 'Current Page'
          }
        ]}
      />
    ),
  },
)
