import React from "react"
import figma from "@figma/code-connect"
import RdsBadge from "./rds-badge"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsBadge,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-Kit?node-id=386-3365",
  {
    props: {
      //changeIcon: figma.instance("🔃 Change Icon"),
      size: figma.enum("📏 Size", {
        Large: "large",
        Medium: "medium",
        Small: "small",
      }),
      shape: figma.enum("⚠️ Shape", {
        Rectangle: "rectangle",
        Pill: "pill",
      }),
      layout: figma.enum("📱 Layout", {
        "Icon only": "Icon_only",
        "Text only": "Text_only",
        "Left Icon+Text": "Icon+Text",
        "Right Icon+Text": "Text+Icon",
      }),
      style: figma.enum("✨ Style", {
        Filled: "filled",
        Outline: "outline",
        Transparent: "transparent",
      }),
      state: figma.enum("💡 State", {
        Default: "default",
        Disabled: "disabled",
      }),
      type: figma.enum("⚠️ Type", {
        Icon: "icon",
        Lottie: "lottie",
      }),
    },
    example: (props) => <RdsBadge  {...props} label={"Badge"} colorVariant="primary" iconName="circle" isIconshow />,
  },
);
