import React from "react"
import RdsCompBarChart from "./rds-comp-chart-bar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompBarChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9857-2655",
  {
    props: {},
    example: (props) => <RdsCompBarChart
    {...props}
  dataSets={[
    {
      backgroundColor: 'rgba(75, 192, 192, 1)',
      borderColor: 'rgba(75, 192, 192, 1)',
      borderRadius: 5,
      borderSkipped: false,
      borderWidth: 2,
      data: [
        20,
        30,
        50,
        80,
        98,
        95,
        55
      ],
      label: 'Fully Radius'
    },
    {
      backgroundColor: 'rgba(54, 162, 235, 1)',
      borderColor: 'rgba(54, 162, 245, 1)',
      borderRadius: 5,
      borderSkipped: false,
      borderWidth: 2,
      data: [
        15,
        67,
        34,
        78,
        45,
        87,
        76
      ],
      label: 'Small Radius'
    }
  ]}
  id={1}
  labels={[
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July'
  ]}
  options={{
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top'
      },
      title: {
        display: true,
        text: 'Border Radius Bar Chart'
      }
    },
    responsive: true,
    scales: {
      x: {
        axis: 'x',
        beginAtZero: false,
        border: {
          color: 'rgba(0,0,0,0.1)',
          dash: [],
          dashOffset: 0,
          display: true,
          width: 1
        },
        bounds: 'ticks',
        clip: true,
        display: true,
        grace: 0,
        grid: {
          color: 'rgba(0,0,0,0.1)',
          display: true,
          drawOnChartArea: true,
          drawTicks: true,
          lineWidth: 1,
          offset: true,
          tickColor: function woe(){},
          tickLength: 8,
          tickWidth: function woe(){}
        },
        id: 'x',
        offset: true,
        position: 'bottom',
        reverse: false,
        ticks: {
          align: 'center',
          autoSkip: true,
          autoSkipPadding: 3,
          backdropColor: 'rgba(255, 255, 255, 0.75)',
          backdropPadding: 2,
          callback: function woe(){},
          color: '#666',
          crossAlign: 'near',
          display: true,
          labelOffset: 0,
          major: {},
          maxRotation: 50,
          minRotation: 0,
          minor: {},
          mirror: false,
          padding: 3,
          showLabelBackdrop: false,
          textStrokeColor: '',
          textStrokeWidth: 0
        },
        title: {
          color: '#666',
          display: false,
          padding: {
            bottom: 4,
            top: 4
          },
          text: ''
        },
        type: 'category'
      },
      y: {
        axis: 'y',
        beginAtZero: true,
        border: {
          color: 'rgba(0,0,0,0.1)',
          dash: [],
          dashOffset: 0,
          display: true,
          width: 1
        },
        bounds: 'ticks',
        clip: true,
        display: true,
        grace: 0,
        grid: {
          color: 'rgba(0,0,0,0.1)',
          display: true,
          drawOnChartArea: true,
          drawTicks: true,
          lineWidth: 1,
          offset: false,
          tickColor: function woe(){},
          tickLength: 8,
          tickWidth: function woe(){}
        },
        id: 'y',
        offset: false,
        position: 'left',
        reverse: false,
        ticks: {
          align: 'center',
          autoSkip: true,
          autoSkipPadding: 3,
          backdropColor: 'rgba(255, 255, 255, 0.75)',
          backdropPadding: 2,
          callback: function woe(){},
          color: '#666',
          crossAlign: 'near',
          display: true,
          labelOffset: 0,
          major: {},
          maxRotation: 50,
          minRotation: 0,
          minor: {},
          mirror: false,
          padding: 3,
          showLabelBackdrop: false,
          textStrokeColor: '',
          textStrokeWidth: 0
        },
        title: {
          color: '#666',
          display: false,
          padding: {
            bottom: 4,
            top: 4
          },
          text: ''
        },
        type: 'linear'
      }
    }
  }}
/>,
  },
)
