import React from "react";
import RdsCompPolarAreaChart from "./rds-comp-chart-polar-area";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompPolarAreaChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9982-1193",
  {
    props: {
      showLegend: figma.boolean("Show Legend"),
    },
    example: (props) => (
      <RdsCompPolarAreaChart
        dataSets={[
          {
            backgroundColor: [
              "rgba(255, 99, 132, 0.2)",
              "rgba(54, 162, 235, 0.2)",
              "rgba(255, 206, 86, 0.2)",
              "rgba(75, 192, 192, 0.2)",
              "rgba(153, 102, 255, 0.2)",
              "rgba(167, 145, 78, 0.2)",
            ],
            borderColor: ["#fff"],
            data: [100, 70, 80, 96, 87, 77],
            label: "Dataset 1",
          },
        ]}
        id="Polar_Area_chart"
        labels={["Red", "Blue", "Yellow", "Green", "Purple", "Orange"]}
        options={{
          animation: {
            animateRotate: true,
            animateScale: false,
          },
          maintainAspectRatio: false,
          plugins: {
            legend: {
              labels: {
                usePointStyle: true,
              },
              pointStyle: "line",
              position: "top",
            },
            title: {
              display: true,
              text: "Polar Area Chart",
            },
            tooltip: {
              usePointStyle: true,
            },
          },
          responsive: true,
          scales: {
            r: {
              angleLines: {
                borderDash: [],
                borderDashOffset: 0,
                color: "rgba(0,0,0,0.1)",
                display: false,
                lineWidth: 1,
              },
              animate: true,
              axis: "r",
              beginAtZero: true,
              border: {
                color: "rgba(0,0,0,0.1)",
                dash: [],
                dashOffset: 0,
                display: true,
                width: 1,
              },
              bounds: "ticks",
              clip: true,
              display: true,
              grace: 0,
              grid: {
                circular: true,
                color: "rgba(0,0,0,0.1)",
                display: true,
                drawOnChartArea: true,
                drawTicks: true,
                lineWidth: 1,
                offset: false,
                tickColor: () => {},
                tickLength: 8,
                tickWidth: () => {},
              },
              id: "r",
              offset: false,
              pointLabels: {
                backdropColor: undefined,
                backdropPadding: 2,
                callback: () => {},
                centerPointLabels: false,
                color: "#666",
                display: false,
                font: {
                  size: 10,
                },
                padding: 5,
              },
              position: "chartArea",
              reverse: false,
              startAngle: 0,
              ticks: {
                align: "center",
                autoSkip: true,
                autoSkipPadding: 3,
                backdropColor: "rgba(255, 255, 255, 0.75)",
                backdropPadding: 2,
                callback: () => {},
                color: "#666",
                crossAlign: "near",
                display: true,
                labelOffset: 0,
                major: {},
                maxRotation: 50,
                minRotation: 0,
                minor: {},
                mirror: false,
                padding: 3,
                showLabelBackdrop: true,
                textStrokeColor: "",
                textStrokeWidth: 0,
              },
              title: {
                color: "#666",
                display: false,
                padding: {
                  bottom: 4,
                  top: 4,
                },
                text: "",
              },
              type: "radialLinear",
            },
          },
        }}
        radius={300}
      />
    ),
  }
);
