name: NPM Publish Storybook
on:
  workflow_dispatch:
permissions: 
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    environment:
      name: "Production"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install and build storybook
        run: |
          npm run install-all
          npm run build-storybook
          
      - name: NPM Install
        run: npm ci
        
      - name: NPM Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.STORYBOOK_NPM_TOKEN }}
