import React from "react"
import RdsInput from "./rds-input"
import figma from "@figma/code-connect"
import { Info } from "@mui/icons-material"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsInput,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=1290-3640",
  {
    props: {
      isMandatory: figma.boolean("❗ Is Mandatory"),
      label: figma.string("✏️ Label"),
      hintText: figma.string("✍ Hint Text"),
      placeholder: figma.string("📝 Placeholder - Text"),
      showIcon: figma.boolean("👀 - Show Icon"),
      layout: figma.enum("📱 Layout", {
        "Text": "text",
        "Password": "password",
        "Phone Number": "phone number",
        "Card Number": "card number"
      }),
      size: figma.enum("📏 Size", {
        "Small": "small",
        "Medium": "medium"
      }),
      style: figma.enum("✨ Style", {
        "Default": "default",
        "Pill": "pill",
        "Bottom Outline": "bottom outline"
      }),
      state: figma.enum("💡 State",  {
        "Default": "default",
        "Active": "active",
        "Selected": "selected",
        "Error": "error",
        "Disabled": "disabled"
      }),
    },
      example: (props) => <RdsInput
      titlePosition="title-above"
      icon={<Info />} iconPosition="end" {...props} />,
  },
)
