import React from "react"
import figma from "@figma/code-connect"
import RdsCompTopNavigation from "./rds-comp-top-navigation"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompTopNavigation,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=975-7912",
  {
    props: {
      showSearch: figma.boolean("🔍 - Show Search"),
      showLogo: figma.boolean("👀 - Show Logo"),

      style: figma.enum("✨ Style", {
        ABP: "ABP",
        RaaghuPortal: "RaaghuPortal",
        Default: "Default"
      }),
    },
    example: (props) => <RdsCompTopNavigation 
    {...props}
    brandLogo="assets/Raaghu-logo-mfe-black.png"
    brandName="Raaghu"
    languageItems={[
      { icon: 'us', iconHeight: '20px', iconWidth: '20px', label: 'EN(US)', val: 'en' },
      { icon: 'in', iconHeight: '20px', iconWidth: '20px', label: 'English(IND)', val: 'en' },
      { icon: 'us', iconHeight: '20px', iconWidth: '20px', label: 'French', val: 'fr' }
    ]}
    logo="https://anzstageui.raaghu.io/assets/raaghu_icon.png"
    navbarSubTitle="Statistics and reports"
    navbarTitle="Dashboard"
    notifications={[
      { selected: false, state: 1, status: 'success', time: 'a month ago', title: 'Tenant added', urlTitle: 'hello', userNotificationId: 0 },
      { selected: false, state: 1, status: 'error', time: 'a month ago', title: 'Tenant deleted', urlTitle: 'hello', userNotificationId: 1 },
      { selected: false, state: 1, status: 'warn', time: 'a month ago', title: 'Tenant added  warn', urlTitle: 'hello', userNotificationId: 2 },
      { selected: false, state: 1, status: 'info', time: 'a month ago', title: 'Tenant deleted info', urlTitle: 'hello', userNotificationId: 3 }
    ]}
    profileEmail="john.doe@raaghu.io"
    profileName="John Doe"
    profileTitle="John Doe"
    role="Admin"
    themeItems={[
      { icon: 'sun', iconHeight: '20px', iconWidth: '20px', label: 'Light', val: 'light' },
      { icon: 'moon', iconHeight: '20px', iconWidth: '20px', label: 'Dark', val: 'dark' }
    ]}
    top_nav_logo="raaghu logo"  
    toggleItems={[]} 
    elementList={[]} 
    componentsList={[]} 
    languageLabel={""} 
    themeLabel={""} 
    onForgotPassword={function (isForgotPasswordClicked?: boolean): void {
      throw new Error("Function not implemented.");
    } } onProfileLinkTopNav={function (id: string, navigateTo?: string, label?: string): void {
      throw new Error("Function not implemented.");
    } }
    />,
  },  
)
