import React from "react"
import RdsCompMixedChart from "./rds-comp-chart-mixed"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompMixedChart,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=9994-1930",
  {
    props: {
      showBarDataset: figma.boolean("Show Bar dataset"),
      showLegend: figma.boolean("Show Legend"),
      showLineDataset: figma.boolean("Show Line Dataset"),
    },
    example: (props) => <RdsCompMixedChart
    {...props}
    dataSets={[
      {
        backgroundColor: 'rgb(248, 188, 198)',
        borderColor: 'rgb(248, 188, 198)',
        data: [
          0,
          37,
          -12,
          70,
          35,
          -32,
          85,
          -24
        ],
        label: 'Bar Dataset',
        order: 0,
        type: 'bar'
      },
      {
        backgroundColor: 'blue',
        borderColor: 'blue',
        data: [
          -10,
          18,
          -60,
          -90,
          -44,
          -91,
          -83,
          46
        ],
        label: 'Line Dataset',
        order: 1,
        type: 'line'
      }
    ]}
    id="mixed_chart"
    labels={[
      'January',
      'February',
      'March',
      'April',
      'May',
      'June'
    ]}
    options={{
      maintainAspectRatio: false,
      plugins: {
        legend: {
          align: 'center',
          labels: {
            usePointStyle: true
          },
          pointStyle: 'bottom',
          position: 'top'
        },
        tooltip: {
          usePointStyle: true
        }
      },
      pointStyle: 'triangle',
      radius: 10,
      responsive: true,
      scales: {
        x: {
          axis: 'x',
          beginAtZero: false,
          border: {
            color: 'rgba(0,0,0,0.1)',
            dash: [],
            dashOffset: 0,
            display: true,
            width: 1
          },
          bounds: 'ticks',
          clip: true,
          display: true,
          grace: 0,
          grid: {
            color: 'rgba(0,0,0,0.1)',
            display: true,
            drawOnChartArea: true,
            drawTicks: true,
            lineWidth: 1,
            offset: true,
            tickColor: () => { },
            tickLength: 8,
            tickWidth: () => { }
          },
          id: 'x',
          offset: true,
          position: 'bottom',
          reverse: false,
          ticks: {
            align: 'center',
            autoSkip: true,
            autoSkipPadding: 3,
            backdropColor: 'rgba(255, 255, 255, 0.75)',
            backdropPadding: 2,
            callback: () => { },
            color: '#666',
            crossAlign: 'near',
            display: true,
            labelOffset: 0,
            major: {},
            maxRotation: 50,
            minRotation: 0,
            minor: {},
            mirror: false,
            padding: 3,
            showLabelBackdrop: false,
            textStrokeColor: '',
            textStrokeWidth: 0
          },
          title: {
            color: '#666',
            display: false,
            padding: {
              bottom: 4,
              top: 4
            },
            text: ''
          },
          type: 'category'
        },
        y: {
          axis: 'y',
          beginAtZero: true,
          border: {
            color: 'rgba(0,0,0,0.1)',
            dash: [],
            dashOffset: 0,
            display: true,
            width: 1
          },
          bounds: 'ticks',
          clip: true,
          display: true,
          grace: 0,
          grid: {
            color: 'rgba(0,0,0,0.1)',
            display: true,
            drawOnChartArea: true,
            drawTicks: true,
            lineWidth: 1,
            offset: false,
            tickColor: () => { },
            tickLength: 8,
            tickWidth: () => { }
          },
          id: 'y',
          offset: false,
          position: 'left',
          reverse: false,
          ticks: {
            align: 'center',
            autoSkip: true,
            autoSkipPadding: 3,
            backdropColor: 'rgba(255, 255, 255, 0.75)',
            backdropPadding: 2,
            callback: () => { },
            color: '#666',
            crossAlign: 'near',
            display: true,
            labelOffset: 0,
            major: {},
            maxRotation: 50,
            minRotation: 0,
            minor: {},
            mirror: false,
            padding: 3,
            showLabelBackdrop: false,
            textStrokeColor: '',
            textStrokeWidth: 0
          },
          title: {
            color: '#666',
            display: false,
            padding: {
              bottom: 4,
              top: 4
            },
            text: ''
          },
          type: 'linear'
        }
      }
    }}
    chartStyle={""}
    />,
  },
)
