import React from "react"
import RdsCompTextEditor from "./rds-comp-text-editor"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RdsCompTextEditor,
  "https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu---Design-System?node-id=385-697",
  {
    props: {
      showTitle: figma.boolean("✏️Show Title"),
      label: figma.string("📝Label"),
      isMandatory: figma.boolean("❗ Is Mandatory"),
      State: figma.enum("💡 State", {
        "Default": "Default",
        "Active": "Active",
        "Selected": "Selected",
        "Disabled": "Disabled",
        "Error": "Error",
      }),

    },
    example: (props) => <RdsCompTextEditor {...props} />,
  },
)
